/**
 * App-level templates: entry point, edge entry point, app factory, env loader.
 *
 * These three files (`src/index.ts`, `src/app.ts`, `src/config/env.ts`) are
 * the closest the scaffold has to "framework code" — they wire arc into
 * the user's project. Keep them in one module so the wiring story stays
 * legible side-by-side.
 */

import type { ProjectConfig } from "../types.js";

export function indexTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  if (config.edge) {
    return edgeIndexTemplate(config);
  }

  return `/**
 * ${config.name} - Server Entry Point
 * Generated by Arc CLI
 *
 * This file starts the HTTP server.
 * For workers or other entry points, import createAppInstance from './app.js'
 */

// Load environment FIRST (before any other imports)
import '#config/env.js';

import config from '#config/index.js';
${config.adapter === "mongokit" ? "import mongoose from 'mongoose';" : ""}
import { createAppInstance } from './app.js';

async function main()${ts ? ": Promise<void>" : ""} {
  console.log(\`Environment: \${config.env}\`);
${
  config.adapter === "mongokit"
    ? `
  // Connect to MongoDB
  await mongoose.connect(config.database.uri);
  console.log('Connected to MongoDB');
`
    : ""
}
  // Create and configure app
  const app = await createAppInstance();

  // Start server
  await app.listen({ port: config.server.port, host: config.server.host });
  console.log(\`Server running at http://\${config.server.host}:\${config.server.port}\`);
}

main().catch((err) => {
  console.error('Failed to start server:', err);
  process.exit(1);
});
`;
}

/**
 * Edge/serverless entry point — exports a Web Standards fetch handler.
 * Works on Cloudflare Workers, AWS Lambda, Vercel Serverless, etc.
 */
function edgeIndexTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  const dbNote =
    config.adapter === "mongokit"
      ? ` *\n * NOTE: Mongoose does NOT work on Cloudflare Workers. This entry point\n * works on AWS Lambda and Vercel Serverless (Node.js runtime) where\n * Mongoose/MongoKit works normally. For Cloudflare Workers, switch to\n * Drizzle + Hyperdrive (PostgreSQL) or the raw mongodb driver.`
      : "";

  return `/**
 * ${config.name} - Edge/Serverless Entry Point
 * Generated by Arc CLI
 *
 * Exports a Web Standards fetch handler that works on:
 * - Cloudflare Workers (enable nodejs_compat in wrangler.toml)
 * - AWS Lambda (via fetch-based adapter)
 * - Vercel Serverless Functions
 * - Any runtime supporting the Web Standards Request/Response API
 *
 * No app.listen() — routes through Fastify's .inject() internally.
${dbNote}
 */

import { toFetchHandler } from '@classytic/arc/factory';
import { createAppInstance } from './app.js';

const app = await createAppInstance();
const handler = toFetchHandler(app);

/**
 * Cloudflare Workers / generic fetch handler
 */
export default {
  async fetch(request${ts ? ": Request" : ""})${ts ? ": Promise<Response>" : ""} {
    return handler(request);
  },
};

/**
 * Named export for platforms that expect it (Vercel, AWS Lambda adapters)
 */
export { handler };
`;
}

export function appTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const typeImport = ts ? "import type { FastifyInstance } from 'fastify';\n" : "";

  const betterAuthImport =
    config.auth === "better-auth"
      ? `import { createBetterAuthAdapter } from '@classytic/arc/auth';
import { getAuth } from './auth.js';
`
      : "";

  // `orgContext: true` even on single-tenant: BA's `organization` plugin
  // is harmless to enable and lets `requireRoles(...)` read org roles the
  // moment a host adds the plugin. Without it, every authenticated
  // request lands as `kind: 'authenticated'` (no orgRoles) and admin-only
  // endpoints 403 — a silent footgun when a single-tenant scaffold opts
  // into the org plugin later. The lookup is a no-op if no plugin exists.
  const authConfig =
    config.auth === "better-auth"
      ? `auth: {
      type: 'betterAuth',
      betterAuth: createBetterAuthAdapter({ auth: getAuth(), orgContext: true }),
    },`
      : `auth: {
      type: 'jwt',
      jwt: { secret: config.jwt.secret },
    },`;

  return `/**
 * ${config.name} - App Factory
 * Generated by Arc CLI
 *
 * Creates and configures the Fastify app instance.
 * Can be imported by:
 * - index.ts (HTTP server via app.listen, or edge handler via toFetchHandler)
 * - worker.ts (background workers)
 * - tests (integration tests via app.inject)
 */

${typeImport}import config from '#config/index.js';
import { createApp } from '@classytic/arc/factory';
${config.adapter === "mongokit" ? "import mongoose from 'mongoose';\n" : ""}${betterAuthImport}
// App-specific plugins
import { registerPlugins } from '#plugins/index.js';

// Resource registry — createApp({ resources }) mounts each one under the
// resourcePrefix below; no manual registration loop needed.
import { resources } from '#resources/index.js';

/**
 * Create a fully configured app instance
 *
 * @returns Configured Fastify instance ready to use
 */
export async function createAppInstance()${ts ? ": Promise<FastifyInstance>" : ""} {
  // Create Arc app with resources and base configuration. \`resourcePrefix\`
  // mounts every resource under \`/api\`, matching the \`apiPrefix\` the
  // OpenAPI plugin advertises — keeps docs and routes in agreement.
  const app = await createApp({
    preset: config.env === 'production' ? (${config.edge ? "'edge'" : "'production'"}) : 'development',
    resources,
    resourcePrefix: '/api',
    ${authConfig}
    cors: {
      origin: config.cors.origins,
      methods: config.cors.methods,
      allowedHeaders: config.cors.allowedHeaders,
      credentials: config.cors.credentials,
    },
    // One proxy hop (the typical LB / reverse-proxy deploy). Widen to a CIDR
    // list or \`true\` only if you know every hop is yours; \`false\` if clients
    // connect directly. Arc's production preset defaults to \`false\` (fail-closed).
    trustProxy: 1,
    arcPlugins: {
      metrics: config.env === 'production',  // Prometheus /_metrics endpoint
${
  config.adapter === "mongokit"
    ? `      // Readiness probe (/_health/ready) reports DOWN until Mongo connects —
      // K8s / load balancers hold traffic until the app can actually serve.
      health: {
        checks: [
          { name: 'mongodb', check: () => mongoose.connection.readyState === 1 },
        ],
      },
`
    : ""
}    },${
    config.adapter === "mongokit"
      ? `
    // Drain the DB connection on shutdown. Arc's gracefulShutdown (on by
    // default) calls app.close() on SIGTERM/SIGINT, which runs this hook —
    // no manual signal handlers needed.
    onClose: async () => {
      await mongoose.disconnect();
    },`
      : ""
  }
  });

  // Register app-specific plugins (explicit dependency injection)
  await registerPlugins(app, { config });

  return app;
}

export default createAppInstance;
`;
}

export function envLoaderTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * Environment Loader
 *
 * MUST be imported FIRST before any other imports.
 * Loads .env files based on NODE_ENV with Next.js-style priority:
 *
 *   .env.local        (always loaded first — gitignored, machine-specific overrides)
 *   .env.{environment} (e.g., .env.production, .env.dev, .env.test)
 *   .env              (fallback defaults)
 *
 * Supports both long-form (production, development, test) and
 * short-form (prod, dev, test) env file names.
 *
 * Usage:
 *   import '#config/env.js';  // First line of entry point
 */

import dotenv from 'dotenv';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

${ts ? "type EnvName = 'prod' | 'dev' | 'test';\n" : ""}const ENV_ALIASES${ts ? ": Record<EnvName, string>" : ""} = {
  prod: 'production',
  dev: 'development',
  test: 'test',
};

function normalizeEnv(env${ts ? ": string | undefined" : ""})${ts ? ": EnvName" : ""} {
  const raw = (env || '').toLowerCase();
  if (raw === 'production' || raw === 'prod') return 'prod';
  if (raw === 'test' || raw === 'qa') return 'test';
  return 'dev';
}

const env = normalizeEnv(process.env.NODE_ENV);
const longForm = ENV_ALIASES[env];

// Priority: .env.local → .env.{long} → .env.{short} → .env
// Same convention as Next.js — .env.local always wins, never committed to git
const candidates = [
  '.env.local',
  \`.env.\${longForm}\`,
  \`.env.\${env}\`,
  '.env',
].map((f) => resolve(process.cwd(), f));

const loaded${ts ? ": string[]" : ""} = [];
for (const file of candidates) {
  if (existsSync(file)) {
    // override: false means earlier files take priority (first loaded wins)
    dotenv.config({ path: file, override: false });
    loaded.push(file.split(/[\\\\/]/).pop() ?? file);
  }
}

// Only log in development (silent in production/test)
if (env === 'dev' && loaded.length > 0) {
  console.log(\`env: \${loaded.join(' + ')}\`);
} else if (loaded.length === 0) {
  console.warn('No .env file found — using process environment only');
}

export const ENV = env;
`;
}
