/**
 * Auth scaffold — five templates split across both auth strategies:
 *
 * - `authResourceTemplate` / `authHandlersTemplate` / `authSchemasTemplate`
 *   / `authTestTemplate` only emit on the JWT path (Better Auth runs its
 *   own routes under `/api/auth/*`).
 * - `betterAuthSetupTemplate` only emits on the Better Auth path and
 *   produces the lazy-singleton config file consumed by `app.ts`.
 *
 * Keeping all five next to each other lets a reader follow the auth
 * story end-to-end without jumping modules.
 */

import type { ProjectConfig } from "../types.js";

export function authResourceTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * Auth Resource
 * Generated by Arc CLI
 *
 * Combined auth + user profile endpoints:
 * - POST /auth/register
 * - POST /auth/login
 * - POST /auth/refresh
 * - POST /auth/forgot-password
 * - POST /auth/reset-password
 * - GET /users/me
 * - PATCH /users/me
 */

import { defineResource } from '@classytic/arc';
import { allowPublic, requireAuth } from '@classytic/arc/permissions';
import { createAdapter } from '#shared/adapter.js';
import User from '../user/user.model.js';
import userRepository from '../user/user.repository.js';
import * as handlers from './auth.handlers.js';
import * as schemas from './auth.schemas.js';

/**
 * Auth Resource - handles authentication
 */
export const authResource = defineResource({
  name: 'auth',
  displayName: 'Authentication',
  tag: 'Authentication',
  prefix: '/auth',

  adapter: createAdapter(User${ts ? " as unknown as never" : ""}, userRepository${ts ? " as unknown as never" : ""}),
  disableDefaultRoutes: true,

  routes: [
    {
      method: 'POST',
      path: '/register',
      summary: 'Register new user',
      permissions: allowPublic(),
      handler: handlers.register,
      raw: true,
      schema: { body: schemas.registerBody, response: { 201: schemas.successResponse } },
    },
    {
      method: 'POST',
      path: '/login',
      summary: 'User login',
      permissions: allowPublic(),
      handler: handlers.login,
      raw: true,
      schema: { body: schemas.loginBody, response: { 200: schemas.loginResponse } },
    },
    {
      method: 'POST',
      path: '/refresh',
      summary: 'Refresh access token',
      permissions: allowPublic(),
      handler: handlers.refreshToken,
      raw: true,
      schema: { body: schemas.refreshBody, response: { 200: schemas.tokenResponse } },
    },
    {
      method: 'POST',
      path: '/forgot-password',
      summary: 'Request password reset',
      permissions: allowPublic(),
      handler: handlers.forgotPassword,
      raw: true,
      schema: { body: schemas.forgotBody, response: { 200: schemas.successResponse } },
    },
    {
      method: 'POST',
      path: '/reset-password',
      summary: 'Reset password with token',
      permissions: allowPublic(),
      handler: handlers.resetPassword,
      raw: true,
      schema: { body: schemas.resetBody, response: { 200: schemas.successResponse } },
    },
  ],
});

/**
 * User Profile Resource - handles /users/me
 */
export const userProfileResource = defineResource({
  name: 'user-profile',
  displayName: 'User Profile',
  tag: 'User Profile',
  prefix: '/users',

  adapter: createAdapter(User${ts ? " as unknown as never" : ""}, userRepository${ts ? " as unknown as never" : ""}),
  disableDefaultRoutes: true,

  routes: [
    {
      method: 'GET',
      path: '/me',
      summary: 'Get current user profile',
      permissions: requireAuth(),
      handler: handlers.getUserProfile,
      raw: true,
      schema: { response: { 200: schemas.userProfileResponse } },
    },
    {
      method: 'PATCH',
      path: '/me',
      summary: 'Update current user profile',
      permissions: requireAuth(),
      handler: handlers.updateUserProfile,
      raw: true,
      schema: { body: schemas.updateUserBody, response: { 200: schemas.userProfileResponse } },
    },
  ],
});

export default authResource;
`;
}

export function betterAuthSetupTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const useMongo = config.adapter === "mongokit";
  const useStubs = useMongo;
  const useOrg = config.tenant === "multi";
  const useBearer = config.session === "bearer" || config.session === "both";
  const useApiKey = config.apiKey;

  // Imports — assembled per-feature so unused symbols don't appear.
  const mongoImport = useMongo
    ? `import mongoose from 'mongoose';
import { mongodbAdapter } from '@better-auth/mongo-adapter';`
    : "";

  const stubsImport = useStubs
    ? `import { registerBetterAuthStubs } from '@classytic/mongokit/better-auth';`
    : "";

  const pluginImports = [
    useOrg ? `import { organization } from 'better-auth/plugins';` : "",
    useBearer ? `import { bearer } from 'better-auth/plugins';` : "",
    useApiKey ? `import { apiKey } from '@better-auth/api-key';` : "",
  ]
    .filter(Boolean)
    .join("\n");

  const dbAdapter = useMongo
    ? config.typescript
      ? `database: mongodbAdapter(mongoose.connection.getClient().db() as unknown as never),`
      : `database: mongodbAdapter(mongoose.connection.getClient().db()),`
    : `// Configure your database adapter here
    // See: https://www.better-auth.com/docs/concepts/database`;

  // Plugin usage — same conditional layering as imports.
  const pluginEntries = [
    useBearer ? `        bearer(),` : "",
    useApiKey
      ? `        apiKey({
          enableMetadata: true,
          rateLimit: { enabled: true, timeWindow: 1000 * 60 * 60 * 24, maxRequests: 10 },
        }),`
      : "",
    useOrg
      ? `        organization({
          allowUserToCreateOrganization: true,
          creatorRole: 'owner',
          teams: { enabled: true },
        }),`
      : "",
  ].filter(Boolean);

  const orgPluginUsage =
    pluginEntries.length > 0
      ? `
      plugins: [
${pluginEntries.join("\n")}
      ],`
      : "";

  // Stub-registration plugin keys — only registers what's enabled.
  const stubPluginsList = [useOrg ? `'organization'` : ""].filter(Boolean).join(", ");
  const stubExtras = useApiKey ? `, extraCollections: ['apikey']` : "";

  const googleProvider = `
      // Google OAuth (enabled when env vars are set)
      ...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
        ? {
            socialProviders: {
              google: {
                clientId: process.env.GOOGLE_CLIENT_ID,
                clientSecret: process.env.GOOGLE_CLIENT_SECRET,
              },
            },
          }
        : {}),`;

  return `/**
 * Better Auth Configuration
 * Generated by Arc CLI
 *
 * Better Auth owns auth flows + writes its own tables. Arc reads them as
 * resources via \`@classytic/mongokit/better-auth\`'s overlay (full pagination,
 * queryparser, OpenAPI, audit) without re-implementing CRUD.
 *
 * BA-managed tables: user, session, account, verification${useOrg ? ", organization, member, invitation, team, teamMember" : ""}${useApiKey ? ", apikey" : ""}
 *
 * @see https://www.better-auth.com/docs
 */

import { betterAuth } from 'better-auth';
${[mongoImport, pluginImports, stubsImport].filter(Boolean).join("\n")}
import config from '#config/index.js';

let _auth${ts ? ": ReturnType<typeof betterAuth> | null" : ""} = null;

/**
 * Get the Better Auth instance (lazy singleton)
 *
 * Must be called AFTER database connection is established.
 */
export function getAuth()${ts ? ": ReturnType<typeof betterAuth>" : ""} {
  if (process.env.NODE_ENV === 'production' && !process.env.BETTER_AUTH_SECRET) {
    throw new Error('BETTER_AUTH_SECRET is required in production (min 32 chars)');
  }

  if (!_auth) {
    _auth = betterAuth({
      secret: config.betterAuth.secret,
      baseURL: process.env.BETTER_AUTH_URL || \`http://localhost:\${config.server.port}\`,
      basePath: '/api/auth',

      ${dbAdapter}
${
  config.tenant === "multi"
    ? `
      user: {
        additionalFields: {
          roles: {
            type: 'string[]',
            defaultValue: ['user'],
            required: false,
            input: false, // Cannot be set during signup
          },
        },
      },
`
    : ""
}
      emailAndPassword: {
        enabled: true,
        minPasswordLength: 6,
      },
${googleProvider}
${orgPluginUsage}
      session: {
        cookieCache: {
          enabled: true,
          maxAge: 5 * 60, // 5 minutes
        },
      },

      trustedOrigins: [config.frontend.url],

      rateLimit: {
        enabled: process.env.NODE_ENV === 'production',
      },
    });
${
  useStubs
    ? `
    // Register stub Mongoose models for Better Auth's collections so
    // \`.populate('user')\` / \`ref: 'organization'\` resolve against BA-owned
    // documents app-wide. Idempotent, strict:false, plugin-aware.
    registerBetterAuthStubs(mongoose, {${stubPluginsList ? ` plugins: [${stubPluginsList}]` : ""}${stubExtras} });
`
    : ""
}  }

  return _auth;
}

export default getAuth;
`;
}

export function authHandlersTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const typeAnnotations = ts
    ? `
import type { FastifyRequest, FastifyReply } from 'fastify';
// Load Arc auth type augmentations (adds request.server.auth typings)
import '@classytic/arc/auth';
`
    : "";

  return `/**
 * Auth Handlers
 * Generated by Arc CLI
 *
 * Uses Arc's built-in JWT utilities via fastify.auth (provided by @fastify/jwt v10).
 * No standalone jsonwebtoken dependency needed.
 */

import userRepository from '../user/user.repository.js';
${typeAnnotations}

/**
 * Register new user
 */
export async function register(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const { name, email, password } = request.body${ts ? " as Record<string, string>" : ""};

    // Check if email exists
    if (await userRepository.emailExists(email)) {
      return reply.code(400).send({ error: 'Email already registered', code: 'arc.email_exists' });
    }

    // Create user
    await userRepository.create({ name, email, password, role: 'user' });

    return reply.code(201).send({ message: 'User registered successfully' });
  } catch (error) {
    request.log.error({ err: error }, 'Register error');
    return reply.code(500).send({ error: 'Registration failed', code: 'arc.internal' });
  }
}

/**
 * Login user
 */
export async function login(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const { email, password } = request.body${ts ? " as Record<string, string>" : ""};

    const user = await userRepository.findByEmail(email);
    if (!user || !(await user.matchPassword(password))) {
      return reply.code(401).send({ error: 'Invalid credentials', code: 'arc.unauthorized' });
    }

    const tokens = request.server.auth.issueTokens({ id: user._id.toString(), role: user.role });

    return reply.send({
      user: { id: user._id, name: user.name, email: user.email, role: user.role },
      ...tokens,
    });
  } catch (error) {
    request.log.error({ err: error }, 'Login error');
    return reply.code(500).send({ error: 'Login failed', code: 'arc.internal' });
  }
}

/**
 * Refresh access token
 */
export async function refreshToken(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const { token } = request.body${ts ? " as { token?: string }" : ""};
    if (!token) {
      return reply.code(401).send({ error: 'Refresh token required', code: 'arc.unauthorized' });
    }

    const decoded = request.server.auth.verifyRefreshToken(token)${ts ? " as { id: string }" : ""};
    const tokens = request.server.auth.issueTokens({ id: decoded.id });

    return reply.send(tokens);
  } catch {
    return reply.code(401).send({ error: 'Invalid refresh token', code: 'arc.unauthorized' });
  }
}

/**
 * Forgot password
 */
export async function forgotPassword(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const { email } = request.body${ts ? " as { email: string }" : ""};
    const user = await userRepository.findByEmail(email);

    if (user) {
      const { randomBytes } = await import('node:crypto');
      const token = randomBytes(32).toString('hex');
      const expires = new Date(Date.now() + 3600000); // 1 hour
      await userRepository.setResetToken(user._id, token, expires);
      // SCAFFOLD: Integrate your email provider to send the reset link
      request.log.info(\`Password reset requested for \${email}\`);
    }

    // Always 200 to prevent email enumeration
    return reply.send({ message: 'If email exists, reset link sent' });
  } catch (error) {
    request.log.error({ err: error }, 'Forgot password error');
    return reply.code(500).send({ error: 'Failed to process request', code: 'arc.internal' });
  }
}

/**
 * Reset password
 */
export async function resetPassword(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const { token, newPassword } = request.body${ts ? " as Record<string, string>" : ""};
    const user = await userRepository.findByResetToken(token);

    if (!user) {
      return reply.code(400).send({ error: 'Invalid or expired token', code: 'arc.bad_request' });
    }

    await userRepository.updatePassword(user._id, newPassword);
    return reply.send({ message: 'Password has been reset' });
  } catch (error) {
    request.log.error({ err: error }, 'Reset password error');
    return reply.code(500).send({ error: 'Failed to reset password', code: 'arc.internal' });
  }
}

/**
 * Get current user profile
 */
export async function getUserProfile(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const requestUser = (request${ts ? " as unknown as { user?: { _id?: string; id?: string } }" : ""}).user;
    const userId = requestUser?._id || requestUser?.id;
    const user = await userRepository.getById(userId);

    if (!user) {
      return reply.code(404).send({ error: 'User not found', code: 'arc.not_found' });
    }

    return reply.send(user);
  } catch (error) {
    request.log.error({ err: error }, 'Get profile error');
    return reply.code(500).send({ error: 'Failed to get profile', code: 'arc.internal' });
  }
}

/**
 * Update current user profile
 */
export async function updateUserProfile(request${ts ? ": FastifyRequest" : ""}, reply${ts ? ": FastifyReply" : ""}) {
  try {
    const requestUser = (request${ts ? " as unknown as { user?: { _id?: string; id?: string } }" : ""}).user;
    const userId = requestUser?._id || requestUser?.id;
    const updates${ts ? ": Record<string, unknown>" : ""} = { ...request.body${ts ? " as Record<string, unknown>" : ""} };

    // Prevent updating protected fields — auth-managed only
    delete updates.password;
    delete updates.role;
    delete updates.organizations;

    const user = await userRepository.Model.findByIdAndUpdate(userId, updates, { new: true });
    return reply.send(user);
  } catch (error) {
    request.log.error({ err: error }, 'Update profile error');
    return reply.code(500).send({ error: 'Failed to update profile', code: 'arc.internal' });
  }
}
`;
}

export function authSchemasTemplate(_config: ProjectConfig): string {
  return `/**
 * Auth Schemas
 * Generated by Arc CLI
 */

export const registerBody = {
  type: 'object',
  required: ['name', 'email', 'password'],
  properties: {
    name: { type: 'string', minLength: 2 },
    email: { type: 'string', format: 'email' },
    password: { type: 'string', minLength: 6 },
  },
};

export const loginBody = {
  type: 'object',
  required: ['email', 'password'],
  properties: {
    email: { type: 'string', format: 'email' },
    password: { type: 'string' },
  },
};

export const refreshBody = {
  type: 'object',
  required: ['token'],
  properties: {
    token: { type: 'string' },
  },
};

export const forgotBody = {
  type: 'object',
  required: ['email'],
  properties: {
    email: { type: 'string', format: 'email' },
  },
};

export const resetBody = {
  type: 'object',
  required: ['token', 'newPassword'],
  properties: {
    token: { type: 'string' },
    newPassword: { type: 'string', minLength: 6 },
  },
};

export const updateUserBody = {
  type: 'object',
  properties: {
    name: { type: 'string', minLength: 2 },
    email: { type: 'string', format: 'email' },
  },
};

// Response schemas (enables fast-json-stringify serialization)

export const successResponse = {
  type: 'object',
  properties: {
    success: { type: 'boolean' },
    message: { type: 'string' },
  },
};

export const loginResponse = {
  type: 'object',
  properties: {
    success: { type: 'boolean' },
    user: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        email: { type: 'string' },
        role: { type: 'string' },
      },
    },
    accessToken: { type: 'string' },
    refreshToken: { type: 'string' },
  },
};

export const tokenResponse = {
  type: 'object',
  properties: {
    success: { type: 'boolean' },
    accessToken: { type: 'string' },
    refreshToken: { type: 'string' },
  },
};

export const userProfileResponse = {
  type: 'object',
  properties: {
    success: { type: 'boolean' },
    data: { type: 'object', additionalProperties: true },
  },
};
`;
}

export function authTestTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * Auth Tests
 * Generated by Arc CLI
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
${config.adapter === "mongokit" ? "import mongoose from 'mongoose';\n" : ""}import { createAppInstance } from '../src/app.js';
${ts ? "import type { FastifyInstance } from 'fastify';\n" : ""}
describe('Auth', () => {
  let app${ts ? ": FastifyInstance" : ""};
  const testUser = {
    name: 'Test User',
    email: 'test@example.com',
    password: 'password123',
  };

  beforeAll(async () => {
${
  config.adapter === "mongokit"
    ? `    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/${config.name}-test';
    await mongoose.connect(testDbUri);
    // Clean up test data
    await mongoose.connection.collection('users').deleteMany({ email: testUser.email });
`
    : ""
}
    app = await createAppInstance();
    await app.ready();
  });

  afterAll(async () => {
${
  config.adapter === "mongokit"
    ? `    await mongoose.connection.collection('users').deleteMany({ email: testUser.email });
    await mongoose.connection.close();
`
    : ""
}    await app.close();
  });

  describe('POST /auth/register', () => {
    it('should register a new user', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/auth/register',
        payload: testUser,
      });

      expect(response.statusCode).toBe(201);
      const body = JSON.parse(response.body);
      expect(body.success).toBe(true);
    });

    it('should reject duplicate email', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/auth/register',
        payload: testUser,
      });

      expect(response.statusCode).toBe(400);
    });
  });

  describe('POST /auth/login', () => {
    it('should login with valid credentials', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/auth/login',
        payload: { email: testUser.email, password: testUser.password },
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body.success).toBe(true);
      expect(body.accessToken).toBeDefined();
      expect(body.refreshToken).toBeDefined();
    });

    it('should reject invalid credentials', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/auth/login',
        payload: { email: testUser.email, password: 'wrongpassword' },
      });

      expect(response.statusCode).toBe(401);
    });
  });

  describe('GET /users/me', () => {
    it('should require authentication', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/users/me',
      });

      expect(response.statusCode).toBe(401);
    });
  });
});
`;
}
