/**
 * Container + edge deployment templates.
 *
 * Docker assets ship for Node.js-server scaffolds; `wrangler.toml`
 * ships for edge/Cloudflare Workers scaffolds. Mutually exclusive
 * (`init` only includes one set per project).
 */

import type { ProjectConfig } from "../types.js";

export function dockerignoreTemplate(): string {
  return `node_modules
dist
.env
.env.*
.git
.vscode
.idea
Dockerfile
docker-compose.yml
coverage
npm-debug.log*
.DS_Store
`;
}

export function dockerfileTemplate(config: ProjectConfig): string {
  return `# Multi-stage Dockerfile for Arc + Fastify
# Optimized for production and caching

# 1. Build Stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
${config.typescript ? "COPY tsconfig*.json ./" : ""}
# If using pnpm, bun, or yarn, adjust the lockfile here
RUN npm ci

COPY . .
${config.typescript ? "RUN npm run build" : ""}

# 2. Production Stage
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --only=production

${config.typescript ? "COPY --from=builder /app/dist ./dist" : "COPY src ./src"}

EXPOSE 8040
CMD ["npm", "start"]
`;
}

export function dockerComposeTemplate(config: ProjectConfig): string {
  let content = `version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8040"
    environment:
      - NODE_ENV=development
      - PORT=8040
      - HOST=0.0.0.0`;

  if (config.adapter === "mongokit") {
    content += `
      - MONGODB_URI=mongodb://mongo:27017/${config.name}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db`;
  }

  content += `

volumes:`;

  if (config.adapter === "mongokit") {
    content += `
  mongo-data:
`;
  }

  return content;
}

export function wranglerTemplate(config: ProjectConfig): string {
  const entry = config.typescript ? "dist/index.js" : "src/index.js";

  // MongoDB requires nodejs_compat_v2 for node:net/tls; others only need nodejs_compat
  const compatFlag = config.adapter === "mongokit" ? "nodejs_compat_v2" : "nodejs_compat";

  let dbConfig = "";

  if (config.adapter === "mongokit") {
    dbConfig = `
# MongoDB Atlas — store URI as a secret:
#   npx wrangler secret put MONGODB_URI
#
# IMPORTANT: Mongoose does NOT work on Workers. Use the raw mongodb driver (6.15+).
# For Lambda/Vercel (Node.js), Mongoose works normally.
`;
  } else {
    dbConfig = `
# Database options for Cloudflare Workers:
#
# PostgreSQL via Hyperdrive (recommended — connection pooling + caching):
#   npx wrangler hyperdrive create my-db --connection-string="postgres://user:pass@host:5432/db"
#   Then uncomment:
# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = "<your-hyperdrive-id>"
#
# Turso (edge SQLite):
#   npx wrangler secret put TURSO_URL
#   npx wrangler secret put TURSO_AUTH_TOKEN
#
# Neon (serverless PostgreSQL via HTTP):
#   npx wrangler secret put DATABASE_URL
#
# D1 (Cloudflare's native SQLite):
# [[d1_databases]]
# binding = "DB"
# database_name = "${config.name}-db"
# database_id = "<run: npx wrangler d1 create ${config.name}-db>"
`;
  }

  return `# Cloudflare Workers configuration
# Generated by Arc CLI — see https://developers.cloudflare.com/workers/

name = "${config.name}"
main = "${entry}"
compatibility_date = "2025-03-20"

# Required for Arc — enables node:crypto and AsyncLocalStorage
compatibility_flags = ["${compatFlag}"]

[vars]
NODE_ENV = "production"

# Secrets (never commit these — use wrangler secret put):
#   npx wrangler secret put JWT_SECRET
${dbConfig}
# Custom domain:
# [routes]
# { pattern = "api.example.com/*", zone_name = "example.com" }
`;
}
