/**
 * Example-resource scaffold — everything under
 * `src/resources/example/` plus its companion `tests/example.test.ts`.
 *
 * Six templates because the scaffold's example follows arc's recommended
 * folder-per-resource layout (model + repository + resource + controller +
 * schemas) and ships a working test alongside.
 */

import type { ProjectConfig } from "../types.js";

export function exampleModelTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const typeExport = ts
    ? `
export type ExampleDocument = mongoose.InferSchemaType<typeof exampleSchema>;
export type ExampleModel = mongoose.Model<ExampleDocument>;
`
    : "";

  return `/**
 * Example Model
 * Generated by Arc CLI
 */

import mongoose from 'mongoose';

const exampleSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true, index: true },
${config.tenant === "multi" ? "    organizationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true, index: true },\n" : ""}    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    deletedAt: { type: Date, default: null, index: true },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes for common queries
exampleSchema.index({ name: 1 });
exampleSchema.index({ deletedAt: 1, isActive: 1 });
${config.tenant === "multi" ? "exampleSchema.index({ organizationId: 1, deletedAt: 1 });\n" : ""}${typeExport}
const Example = mongoose.model${ts ? "<ExampleDocument>" : ""}('Example', exampleSchema);

export default Example;
`;
}

export function exampleRepositoryTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const typeImport = ts ? "import type { ExampleDocument } from './example.model.js';\n" : "";
  const generic = ts ? "<ExampleDocument>" : "";

  return `/**
 * Example Repository
 * Generated by Arc CLI
 *
 * MongoKit repository with plugins for:
 * - Soft delete (deletedAt filtering)
 * - Custom business logic methods
 */

import {
  Repository,
  softDeletePlugin,
  methodRegistryPlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
${typeImport}import Example from './example.model.js';

class ExampleRepository extends Repository${generic} {
  constructor() {
    super(Example, [
      methodRegistryPlugin(),
      softDeletePlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find all active (non-deleted) records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }
${
  config.tenant === "multi"
    ? `
  /**
   * Find active records for an organization
   */
  async findActiveByOrg(organizationId${ts ? ": string" : ""}) {
    return this.Model.find({
      organizationId,
      isActive: true,
      deletedAt: null,
    }).lean();
  }
`
    : ""
}
  // Note: softDeletePlugin provides restore() and getDeleted() methods automatically
}

const exampleRepository = new ExampleRepository();

export default exampleRepository;
export { ExampleRepository };
`;
}

export function exampleResourceTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * Example Resource
 * Generated by Arc CLI
 *
 * A complete resource with:
 * - Model (Mongoose schema)
 * - Repository (MongoKit with plugins)
 * - Permissions (role-based access)
 * - Presets (soft delete${config.tenant === "multi" ? ", multi-tenant" : ""})
 */

import { defineResource } from '@classytic/arc';
import { QueryParser } from '@classytic/mongokit';
import { createAdapter } from '#shared/adapter.js';
import { ${config.tenant === "multi" ? "orgStaffPermissions" : "publicReadPermissions"} } from '#shared/permissions.js';
${config.tenant === "multi" ? "import { flexibleMultiTenantPreset } from '#shared/presets/flexible-multi-tenant.js';\n" : ""}import Example${ts ? ", { type ExampleDocument }" : ""} from './example.model.js';
import exampleRepository from './example.repository.js';
import exampleController from './example.controller.js';

const queryParser = new QueryParser({
  allowedFilterFields: ['isActive'],
});

const exampleResource = defineResource${ts ? "<ExampleDocument>" : ""}({
  name: 'example',
  displayName: 'Examples',
  prefix: '/examples',

  adapter: createAdapter(Example, exampleRepository),
  controller: exampleController,
  queryParser,

  presets: [
    'softDelete',
    'bulk',${
      config.tenant === "multi"
        ? `
    flexibleMultiTenantPreset({ tenantField: 'organizationId' }),`
        : ""
    }
  ],

  permissions: ${config.tenant === "multi" ? "orgStaffPermissions" : "publicReadPermissions"},

  // Add custom routes here:
  // routes: [
  //   {
  //     method: 'GET',
  //     path: '/custom',
  //     summary: 'Custom endpoint',
  //     handler: async (request, reply) => { ... },
  //   },
  // ],
});

export default exampleResource;
`;
}

export function exampleControllerTemplate(config: ProjectConfig): string {
  return `/**
 * Example Controller
 * Generated by Arc CLI
 *
 * BaseController provides CRUD operations with:
 * - Automatic pagination
 * - Query parsing
 * - Validation
 */

import { BaseController } from '@classytic/arc';
import exampleRepository from './example.repository.js';
import { exampleSchemaOptions } from './example.schemas.js';

class ExampleController extends BaseController {
  constructor() {
    super(exampleRepository, {
      schemaOptions: exampleSchemaOptions,${
        config.tenant === "multi"
          ? `
      tenantField: 'organizationId', // Configurable tenant field for multi-tenant`
          : `
      // tenantField: 'organizationId', // For multi-tenant apps`
      }
    });
  }

  // Add custom controller methods here:
  // async customAction(request, reply) {
  //   // Custom logic
  // }
}

const exampleController = new ExampleController();
export default exampleController;
`;
}

export function exampleSchemasTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const multiTenantFields = config.tenant === "multi";

  return `/**
 * Example Schemas
 * Generated by Arc CLI
 *
 * Schema options for controller validation and query parsing
 */

import Example from './example.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 * Auto-generated from Mongoose model
 */
const crudSchemas = buildCrudSchemasFromModel(Example, {
  strictAdditionalProperties: true,
  fieldRules: {
    // Framework-injected fields — strip from body + required[]
    // deletedAt: { systemManaged: true },
    // Legitimate null values (Zod .nullable() patterns) — widen JSON-Schema type
    // priceMode: { nullable: true },
    // Elevated-admin override for systemManaged fields (cross-tenant writes)
    // organizationId: { systemManaged: true, preserveForElevated: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',${
        multiTenantFields
          ? `
      organizationId: 'ObjectId',`
          : ""
      }
      createdAt: 'date',
    },
  },
});

// Schema options for controller
export const exampleSchemaOptions${ts ? ": Record<string, unknown>" : ""} = {
  query: {${
    multiTenantFields
      ? `
    allowedPopulate: ['organizationId'],`
      : ""
  }
    filterableFields: {
      isActive: 'boolean',${
        multiTenantFields
          ? `
      organizationId: 'ObjectId',`
          : ""
      }
      createdAt: 'date',
    },
  },
};

export default crudSchemas;
`;
}

export function exampleTestTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * Example Resource Tests
 * Generated by Arc CLI
 *
 * Run tests: npm test
 * Watch mode: npm run test:watch
 *
 * Uses arc's 2.11 testing surface:
 *   - createTestApp  — turnkey Fastify + in-memory Mongo + auth + fixtures
 *   - expectArc      — fluent envelope matchers (.ok, .unauthorized, .forbidden, ...)
 *   - ctx.auth       — unified TestAuthProvider, register a role once then reuse .headers
 */

import { describe, it, beforeAll, afterAll } from 'vitest';
import { createTestApp, expectArc } from '@classytic/arc/testing';
import type { TestAppContext } from '@classytic/arc/testing';
import { exampleResource } from '../src/resources/example/example.js';

describe('Example Resource', () => {
  let ctx${ts ? ": TestAppContext" : ""};

  beforeAll(async () => {
    ctx = await createTestApp({
      resources: [exampleResource],
      authMode: 'jwt',
${config.adapter === "mongokit" ? "      connectMongoose: true,\n" : ""}    });

    // Arc's permission engine reads singular user.role — string,
    // comma-separated string, or array all normalise via getUserRoles().
    ctx.auth${ts ? "!" : ""}.register('admin', {
      user: { id: '1', role: 'admin' },
      orgId: 'org-1',
    });
  });

  afterAll(() => ctx.close());

  describe('GET /examples', () => {
    it('should return a list of examples (public)', async () => {
      const res = await ctx.app.inject({ method: 'GET', url: '/examples' });
      expectArc(res).ok().paginated();
    });
  });

  describe('POST /examples', () => {
    it('should require authentication', async () => {
      const res = await ctx.app.inject({
        method: 'POST',
        url: '/examples',
        payload: { name: 'Test Example' },
      });
      expectArc(res).unauthorized();
    });

    it('should create when admin is authenticated', async () => {
      const res = await ctx.app.inject({
        method: 'POST',
        url: '/examples',
        headers: ctx.auth${ts ? "!" : ""}.as('admin').headers,
        payload: { name: 'Test Example' },
      });
      expectArc(res).ok();
    });
  });

  // Add more tests as needed:
  // - GET /examples/:id         (expectArc(res).ok().hasData({ name: '...' }))
  // - PATCH /examples/:id       (expectArc(res).ok())
  // - DELETE /examples/:id      (expectArc(res).ok())
  // - Custom endpoints
  // - Permission denials        (expectArc(res).forbidden().hasError(/reason/))
  // - Field hiding              (expectArc(res).hidesField('password'))
});
`;
}
