/**
 * User-resource scaffold — only emitted for the JWT auth path. Better
 * Auth manages its own user tables, so this whole module is skipped
 * when `config.auth === 'better-auth'`.
 */

import type { ProjectConfig } from "../types.js";

export function userModelTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  const orgRoles =
    config.tenant === "multi"
      ? `
// Organization roles (for multi-tenant)
const ORG_ROLES = ['owner', 'manager', 'hr', 'staff', 'contractor'] as const;
type OrgRole = typeof ORG_ROLES[number];
`
      : "";

  const orgInterface =
    config.tenant === "multi"
      ? `
type UserOrganization = {
  organizationId: Types.ObjectId;
  organizationName: string;
  roles: OrgRole[];
  joinedAt: Date;
};
`
      : "";

  const orgSchema =
    config.tenant === "multi"
      ? `
    // Multi-org support
    organizations: [{
      organizationId: { type: Schema.Types.ObjectId, ref: 'Organization', required: true },
      organizationName: { type: String, required: true },
      roles: { type: [String], enum: ORG_ROLES, default: [] },
      joinedAt: { type: Date, default: () => new Date() },
    }],
`
      : "";

  const orgMethods =
    config.tenant === "multi"
      ? `
// Organization methods
userSchema.methods.getOrgRoles = function(orgId${ts ? ": Types.ObjectId | string" : ""}) {
  const org = this.organizations.find(o => o.organizationId.toString() === orgId.toString());
  return org?.roles || [];
};

userSchema.methods.hasOrgAccess = function(orgId${ts ? ": Types.ObjectId | string" : ""}) {
  return this.organizations.some(o => o.organizationId.toString() === orgId.toString());
};

userSchema.methods.addOrganization = function(
  organizationId${ts ? ": Types.ObjectId" : ""},
  organizationName${ts ? ": string" : ""},
  roles${ts ? ": OrgRole[]" : ""} = []
) {
  const existing = this.organizations.find(o => o.organizationId.toString() === organizationId.toString());
  if (existing) {
    existing.organizationName = organizationName;
    existing.roles = [...new Set([...existing.roles, ...roles])];
  } else {
    this.organizations.push({ organizationId, organizationName, roles, joinedAt: new Date() });
  }
  return this;
};

userSchema.methods.removeOrganization = function(organizationId${ts ? ": Types.ObjectId" : ""}) {
  this.organizations = this.organizations.filter(o => o.organizationId.toString() !== organizationId.toString());
  return this;
};

// Index for org queries
userSchema.index({ 'organizations.organizationId': 1 });
`
      : "";

  const userType = ts
    ? `
type User = {
  name: string;
  email: string;
  password: string;
  // Platform role(s), Better Auth admin-plugin convention: a single role
  // ('admin') or a comma-separated list ('admin,trainer'). Arc's permission
  // engine normalises both forms via getUserRoles() — see @classytic/arc/scope.
  role: string;${
    config.tenant === "multi"
      ? `
  organizations: UserOrganization[];`
      : ""
  }
  resetPasswordToken?: string;
  resetPasswordExpires?: Date;
};

type UserMethods = {
  matchPassword: (enteredPassword: string) => Promise<boolean>;${
    config.tenant === "multi"
      ? `
  getOrgRoles: (orgId: Types.ObjectId | string) => OrgRole[];
  hasOrgAccess: (orgId: Types.ObjectId | string) => boolean;
  addOrganization: (orgId: Types.ObjectId, name: string, roles?: OrgRole[]) => UserDocument;
  removeOrganization: (orgId: Types.ObjectId) => UserDocument;`
      : ""
  }
};

export type UserDocument = HydratedDocument<User, UserMethods>;
export type UserModel = Model<User, Record<string, never>, UserMethods>;
`
    : "";

  return `/**
 * User Model
 * Generated by Arc CLI
 */

import bcrypt from 'bcryptjs';
import mongoose${ts ? `, { type HydratedDocument, type Model${config.tenant === "multi" ? ", type Types" : ""} }` : ""} from 'mongoose';
${orgRoles}
const { Schema } = mongoose;
${orgInterface}${userType}
const userSchema = new Schema${ts ? "<User, UserModel, UserMethods>" : ""}(
  {
    name: { type: String, required: true, trim: true },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    password: { type: String, required: true },

    // Platform role — singular field, matches Arc's permission engine
    // (req.user.role) and Better Auth's admin-plugin convention.
    // Comma-separated for multi-role users (e.g. 'admin,trainer');
    // getUserRoles() in @classytic/arc/scope normalises both forms.
    role: {
      type: String,
      required: true,
      default: 'user',
      index: true,
      validate: {
        validator: (v${ts ? ": string" : ""}) =>
          /^(user|admin|superadmin)(,(user|admin|superadmin))*$/.test(v),
        message: (props${ts ? ": { value: string }" : ""}) =>
          \`Invalid role "\${props.value}" — expected one or more of user|admin|superadmin\`,
      },
    },
${orgSchema}
    // Password reset
    resetPasswordToken: String,
    resetPasswordExpires: Date,
  },
  { timestamps: true }
);

// Password hashing
userSchema.pre('save', async function() {
  if (!this.isModified('password')) return;
  const salt = await bcrypt.genSalt(10);
  this.password = await bcrypt.hash(this.password, salt);
});

// Password comparison
userSchema.methods.matchPassword = async function(enteredPassword${ts ? ": string" : ""}) {
  return bcrypt.compare(enteredPassword, this.password);
};
${orgMethods}
// Exclude password in JSON
userSchema.set('toJSON', {
  transform: (_doc, ret${ts ? ": Record<string, unknown>" : ""}) => {
    delete ret.password;
    delete ret.resetPasswordToken;
    delete ret.resetPasswordExpires;
    return ret;
  },
});

const User = mongoose.models.User${ts ? " as UserModel" : ""} || mongoose.model${ts ? "<User, UserModel>" : ""}('User', userSchema);
export default User;
`;
}

export function userRepositoryTemplate(config: ProjectConfig): string {
  const ts = config.typescript;
  const typeImport = ts
    ? "import type { UserDocument } from './user.model.js';\nimport type { ClientSession, Types } from 'mongoose';\n"
    : "";

  return `/**
 * User Repository
 * Generated by Arc CLI
 *
 * MongoKit repository with plugins for common operations
 */

import {
  Repository,
  methodRegistryPlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
${typeImport}import User from './user.model.js';

${ts ? "type ID = string | Types.ObjectId;\n" : ""}
class UserRepository extends Repository${ts ? "<UserDocument>" : ""} {
  constructor() {
    super(User${ts ? " as unknown as never" : ""}, [
      methodRegistryPlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find user by email
   */
  async findByEmail(email${ts ? ": string" : ""}) {
    return this.Model.findOne({ email: email.toLowerCase().trim() });
  }

  /**
   * Find user by reset token
   */
  async findByResetToken(token${ts ? ": string" : ""}) {
    return this.Model.findOne({
      resetPasswordToken: token,
      resetPasswordExpires: { $gt: Date.now() },
    });
  }

  /**
   * Check if email exists
   */
  async emailExists(email${ts ? ": string" : ""})${ts ? ": Promise<boolean>" : ""} {
    const result = await this.Model.exists({ email: email.toLowerCase().trim() });
    return !!result;
  }

  /**
   * Update user password (triggers hash middleware)
   */
  async updatePassword(userId${ts ? ": ID" : ""}, newPassword${ts ? ": string" : ""}, options${ts ? ": { session?: ClientSession }" : ""} = {}) {
    const user = await this.Model.findById(userId).session(options.session ?? null);
    if (!user) throw new Error('User not found');

    user.password = newPassword;
    user.resetPasswordToken = undefined;
    user.resetPasswordExpires = undefined;
    await user.save({ session: options.session ?? undefined });
    return user;
  }

  /**
   * Set reset token
   */
  async setResetToken(userId${ts ? ": ID" : ""}, token${ts ? ": string" : ""}, expiresAt${ts ? ": Date" : ""}) {
    return this.Model.findByIdAndUpdate(
      userId,
      { resetPasswordToken: token, resetPasswordExpires: expiresAt },
      { new: true }
    );
  }
${
  config.tenant === "multi"
    ? `
  /**
   * Find users by organization
   */
  async findByOrganization(organizationId${ts ? ": ID" : ""}) {
    return this.Model.find({ 'organizations.organizationId': organizationId })
      .select('-password -resetPasswordToken -resetPasswordExpires')
      .lean();
  }
`
    : ""
}
}

const userRepository = new UserRepository();
export default userRepository;
export { UserRepository };
`;
}

export function userControllerTemplate(config: ProjectConfig): string {
  const ts = config.typescript;

  return `/**
 * User Controller
 * Generated by Arc CLI
 *
 * BaseController for user management operations.
 * Used by auth resource for /users/me endpoints.
 */

import { BaseController } from '@classytic/arc';
import userRepository from './user.repository.js';

class UserController extends BaseController {
  constructor() {
    super(userRepository${ts ? " as unknown as never" : ""});
  }

  // Custom user operations can be added here
}

const userController = new UserController();
export default userController;
`;
}
