/**
 * Arc CLI — Runtime Verification
 *
 * Verifies that the patterns generated by `arc init` and `arc generate`
 * actually work at runtime:
 *
 * 1. MongoKit Repository<TDoc> + QueryParser → defineResource → working CRUD
 * 2. QueryParser.allowedFilterFields flow through to MCP tool schemas
 * 3. createMongooseAdapter({ model, repository }) wiring is correct
 * 4. MCP discovers tools with correct input schemas from the resource
 *
 * Uses mongodb-memory-server (same as other e2e tests) with the test DB.
 */

import {
  methodRegistryPlugin,
  mongoOperationsPlugin,
  QueryParser,
  Repository,
  softDeletePlugin,
} from "@classytic/mongokit";
import { createMongooseAdapter } from "@classytic/mongokit/adapter";
import { MongoMemoryServer } from "mongodb-memory-server";
import mongoose from "mongoose";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { BaseController } from "../../src/core/BaseController.js";
import { defineResource } from "../../src/core/defineResource.js";
import { resourceToTools } from "../../src/integrations/mcp/resourceToTools.js";
import { createTestMcpClient } from "../../src/integrations/mcp/testing.js";
import { allowPublic } from "../../src/permissions/index.js";

// ============================================================================
// Setup — mirrors what `arc init` + `arc generate` produce
// ============================================================================

let mongod: MongoMemoryServer;

// 1. Model (same pattern as arc generate model template)
interface IProduct {
  name: string;
  description?: string;
  price: number;
  category: string;
  isActive: boolean;
}

const productSchema = new mongoose.Schema<IProduct>(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    price: { type: Number, required: true, min: 0 },
    category: {
      type: String,
      enum: ["electronics", "clothing", "books"],
      required: true,
    },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true },
);

productSchema.index({ category: 1, isActive: 1 });

const ProductModel =
  mongoose.models.CLITestProduct || mongoose.model("CLITestProduct", productSchema);

// 2. Repository (same pattern as arc generate repository template)
class ProductRepository extends Repository<IProduct> {
  constructor() {
    super(ProductModel, [methodRegistryPlugin(), softDeletePlugin(), mongoOperationsPlugin()]);
  }

  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }
}

const productRepository = new ProductRepository();

// 3. QueryParser (same pattern as arc generate resource template)
const queryParser = new QueryParser({
  allowedFilterFields: ["category", "isActive"],
  allowedSortFields: ["name", "price", "createdAt"],
  allowedOperators: ["eq", "ne", "in", "gt", "lt"],
});

// 4. Controller (same pattern as arc generate controller template)
const productController = new BaseController(productRepository, {
  resourceName: "product",
  queryParser,
  tenantField: false,
});

// 5. Resource (same pattern as arc generate resource template)
const productResource = defineResource({
  name: "product",
  displayName: "Products",
  adapter: createMongooseAdapter({ model: ProductModel, repository: productRepository }),
  controller: productController,
  queryParser,
  permissions: {
    list: allowPublic(),
    get: allowPublic(),
    create: allowPublic(),
    update: allowPublic(),
    delete: allowPublic(),
  },
  schemaOptions: {
    fieldRules: {
      name: { type: "string", required: true, description: "Product name" },
      description: { type: "string", description: "Product description" },
      price: { type: "number", required: true, min: 0, description: "Price in USD" },
      category: {
        type: "string",
        enum: ["electronics", "clothing", "books"],
        required: true,
        description: "Product category",
      },
      isActive: { type: "boolean", description: "Whether product is active" },
      createdAt: { type: "date", systemManaged: true },
      updatedAt: { type: "date", systemManaged: true },
    },
    filterableFields: ["category", "isActive"],
  },
});

// ============================================================================
// Lifecycle
// ============================================================================

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  await mongoose.connect(mongod.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongod.stop();
});

// ============================================================================
// 1. MongoKit Repository + QueryParser → CRUD at runtime
// ============================================================================

describe("Runtime: MongoKit Repository + QueryParser → CRUD", () => {
  let createdId: string;

  it("creates a document via repository", async () => {
    const doc = await productRepository.create({
      name: "TypeScript Handbook",
      price: 39.99,
      category: "books",
      isActive: true,
    });
    expect(doc).toBeDefined();
    createdId = (doc as any)._id.toString();
    expect(createdId).toBeTruthy();
  });

  it("lists documents via repository with QueryParser filtering", async () => {
    // Create another in a different category
    await productRepository.create({
      name: "Laptop",
      price: 999,
      category: "electronics",
      isActive: true,
    });

    // QueryParser should parse filter correctly
    const parsed = queryParser.parse({ category: "books" });
    expect(parsed.filters).toEqual({ category: "books" });

    const result = await productRepository.getAll({
      filter: parsed.filters,
      sort: parsed.sort,
      page: parsed.page,
      limit: parsed.limit,
    });

    // May include soft-deleted doc — at least one should be the book
    expect(result.data.length).toBeGreaterThanOrEqual(1);
    expect(result.data.some((d: any) => d.name === "TypeScript Handbook")).toBe(true);
  });

  it("QueryParser rejects disallowed filter fields", () => {
    const parsed = queryParser.parse({ price: { $gt: 100 } });
    // price is NOT in allowedFilterFields, so it should be dropped
    expect(parsed.filters).not.toHaveProperty("price");
  });

  it("QueryParser accepts allowed filter fields with eq", () => {
    const parsed = queryParser.parse({ category: "electronics" });
    expect(parsed.filters).toHaveProperty("category");
    expect(parsed.filters.category).toBe("electronics");
  });

  it("getById works via repository", async () => {
    const doc = await productRepository.getById(createdId);
    expect(doc).toBeDefined();
    expect((doc as any).name).toBe("TypeScript Handbook");
  });

  it("update works via repository", async () => {
    const updated = await productRepository.update(createdId, { price: 49.99 });
    expect((updated as any).price).toBe(49.99);
  });

  it("delete works via repository", async () => {
    // softDeletePlugin marks as deleted
    const result = await productRepository.delete(createdId);
    expect(result).toBeDefined();
  });
});

// ============================================================================
// 2. defineResource → resourceToTools — correct MCP tool schemas
// ============================================================================

describe("Runtime: defineResource → MCP tool schemas", () => {
  let tools: ReturnType<typeof resourceToTools>;

  beforeAll(() => {
    tools = resourceToTools(productResource);
  });

  it("generates all 5 CRUD tools", () => {
    expect(tools).toHaveLength(5);
    expect(tools.map((t) => t.name)).toEqual([
      "list_products",
      "get_product",
      "create_product",
      "update_product",
      "delete_product",
    ]);
  });

  it("list tool has filterable fields from QueryParser in schema", () => {
    const listTool = tools.find((t) => t.name === "list_products")!;
    expect(listTool.inputSchema).toHaveProperty("category");
    expect(listTool.inputSchema).toHaveProperty("isActive");
    // price is NOT filterable
    expect(listTool.inputSchema).not.toHaveProperty("price");
    // pagination always present
    expect(listTool.inputSchema).toHaveProperty("page");
    expect(listTool.inputSchema).toHaveProperty("limit");
    expect(listTool.inputSchema).toHaveProperty("sort");
  });

  it("list tool description includes filterable fields", () => {
    const listTool = tools.find((t) => t.name === "list_products")!;
    expect(listTool.description).toContain("category");
    expect(listTool.description).toContain("isActive");
    expect(listTool.description).toContain("Filterable fields");
  });

  it("list tool description includes allowed operators", () => {
    const listTool = tools.find((t) => t.name === "list_products")!;
    expect(listTool.description).toContain("eq");
    expect(listTool.description).toContain("Filter operators");
  });

  it("list tool description includes sortable fields", () => {
    const listTool = tools.find((t) => t.name === "list_products")!;
    expect(listTool.description).toContain("name");
    expect(listTool.description).toContain("price");
    expect(listTool.description).toContain("Sortable fields");
  });

  it("create tool has required fields in schema", () => {
    const createTool = tools.find((t) => t.name === "create_product")!;
    expect(createTool.inputSchema).toHaveProperty("name");
    expect(createTool.inputSchema).toHaveProperty("price");
    expect(createTool.inputSchema).toHaveProperty("category");
    // systemManaged fields excluded
    expect(createTool.inputSchema).not.toHaveProperty("createdAt");
    expect(createTool.inputSchema).not.toHaveProperty("updatedAt");
  });

  it("category field has enum constraint in create schema", () => {
    const createTool = tools.find((t) => t.name === "create_product")!;
    const categoryProp = (createTool.inputSchema as any).category;
    // enum may be array or key-value map depending on fieldRulesToZod output
    const enumValues = Array.isArray(categoryProp.enum)
      ? categoryProp.enum
      : Object.values(categoryProp.enum);
    expect(enumValues).toEqual(expect.arrayContaining(["electronics", "clothing", "books"]));
  });

  it("tools have correct annotations", () => {
    const listTool = tools.find((t) => t.name === "list_products")!;
    const deleteTool = tools.find((t) => t.name === "delete_product")!;
    expect(listTool.annotations?.readOnlyHint).toBe(true);
    expect(deleteTool.annotations?.destructiveHint).toBe(true);
  });
});

// ============================================================================
// 3. MCP end-to-end — createTestMcpClient with the resource
// ============================================================================

describe("Runtime: MCP end-to-end via createTestMcpClient", () => {
  let client: Awaited<ReturnType<typeof createTestMcpClient>>;

  beforeAll(async () => {
    // Seed fresh data for MCP tests
    await ProductModel.deleteMany({});
    await ProductModel.create([
      { name: "Keyboard", price: 79, category: "electronics", isActive: true },
      { name: "Novel", price: 15, category: "books", isActive: true },
      { name: "T-Shirt", price: 25, category: "clothing", isActive: false },
    ]);

    client = await createTestMcpClient({
      pluginOptions: {
        resources: [productResource],
        instructions: "Test MCP server with products.",
      },
      auth: { userId: "test-user", organizationId: "org-1" },
    });
  });

  afterAll(async () => {
    await client.close();
  });

  it("lists all tools via MCP protocol", async () => {
    const tools = await client.listTools();
    const names = tools.map((t) => t.name);
    expect(names).toContain("list_products");
    expect(names).toContain("get_product");
    expect(names).toContain("create_product");
    expect(names).toContain("update_product");
    expect(names).toContain("delete_product");
  });

  it("list_products returns all items via MCP", async () => {
    const result = await client.callTool("list_products", {});
    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0]?.text);
    expect(data.data).toHaveLength(3);
  });

  it("list_products filters by category via MCP", async () => {
    const result = await client.callTool("list_products", { category: "books" });
    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0]?.text);
    expect(data.data).toHaveLength(1);
    expect(data.data[0].name).toBe("Novel");
  });

  it("list_products filters by isActive via MCP", async () => {
    const result = await client.callTool("list_products", { isActive: false });
    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0]?.text);
    expect(data.data).toHaveLength(1);
    expect(data.data[0].name).toBe("T-Shirt");
  });

  it("create_product creates via MCP", async () => {
    const result = await client.callTool("create_product", {
      name: "Headphones",
      price: 199,
      category: "electronics",
    });
    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0]?.text);
    expect(data.data?.name || data.name).toBe("Headphones");
  });

  it("get_product retrieves by ID via MCP", async () => {
    const listResult = await client.callTool("list_products", { category: "electronics" });
    const list = JSON.parse(listResult.content[0]?.text);
    const id = (list.data ?? list)[0]._id;

    const result = await client.callTool("get_product", { id });
    expect(result.isError).toBeFalsy();
    const data = JSON.parse(result.content[0]?.text);
    expect(data.data?._id || data._id).toBe(id);
  });

  it("update_product updates via MCP", async () => {
    const listResult = await client.callTool("list_products", { category: "books" });
    const id = JSON.parse(listResult.content[0]?.text).data[0]._id;

    const result = await client.callTool("update_product", { id, price: 19.99 });
    expect(result.isError).toBeFalsy();
  });

  it("delete_product deletes via MCP", async () => {
    const listResult = await client.callTool("list_products", { category: "clothing" });
    const id = JSON.parse(listResult.content[0]?.text).data[0]._id;

    const result = await client.callTool("delete_product", { id });
    expect(result.isError).toBeFalsy();
  });
});

// ============================================================================
// 4. QueryParser auto-derivation — no explicit filterableFields
// ============================================================================

describe("Runtime: QueryParser auto-derive (no explicit filterableFields)", () => {
  it("auto-derives filterable fields from QueryParser when schemaOptions omits them", () => {
    const parser = new QueryParser({
      allowedFilterFields: ["status", "priority"],
      allowedOperators: ["eq", "in"],
    });

    const resource = defineResource({
      name: "task",
      displayName: "Tasks",
      adapter: createMongooseAdapter({ model: ProductModel, repository: productRepository }),
      controller: new BaseController(productRepository, {
        resourceName: "task",
        queryParser: parser,
        tenantField: false,
      }),
      queryParser: parser,
      permissions: { list: allowPublic(), get: allowPublic() },
      schemaOptions: {
        fieldRules: {
          title: { type: "string", required: true },
          status: { type: "string", enum: ["open", "closed"] },
          priority: { type: "string", enum: ["low", "high"] },
          assignee: { type: "string" },
        },
        // NOTE: no filterableFields — should auto-derive from QueryParser
      },
    });

    const tools = resourceToTools(resource);
    const listTool = tools.find((t) => t.name === "list_tasks")!;

    // Auto-derived from QueryParser.allowedFilterFields
    expect(listTool.inputSchema).toHaveProperty("status");
    expect(listTool.inputSchema).toHaveProperty("priority");
    // assignee is NOT in allowedFilterFields
    expect(listTool.inputSchema).not.toHaveProperty("assignee");
  });
});
