/**
 * Full Application E2E Test
 *
 * Tests complete application flow: factory initialization, resource registration,
 * CRUD operations, hooks, authentication, and more
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createApp } from '../../src/factory/createApp.js';
import { defineResource } from '../../src/core/defineResource.js';
import { BaseController } from '../../src/core/BaseController.js';
import { createMongooseAdapter } from '../../src/adapters/mongoose.js';
import { allowPublic } from '../../src/permissions/index.js';
import { setupTestDatabase, teardownTestDatabase, createMockModel, createMockRepository } from '../setup.js';
import type { FastifyInstance } from 'fastify';

describe('Full Application E2E', () => {
  let app: FastifyInstance;
  let mongoUri: string;
  const testPort = 3001;

  beforeAll(async () => {
    // Setup test database
    mongoUri = await setupTestDatabase();

    // Create test models
    const ProductModel = createMockModel('E2EProduct');
    const productRepo = createMockRepository(ProductModel);
    const productController = new BaseController(productRepo);

    // Define resource with hooks
    const productResource = defineResource({
      name: 'product',
      adapter: createMongooseAdapter({
        model: ProductModel,
        repository: productRepo,
      }),
      controller: productController,
      prefix: '/products',
      tag: 'Products',
      permissions: {
        list: allowPublic(),
        get: allowPublic(),
        create: allowPublic(),
        update: allowPublic(),
        delete: allowPublic(),
      },
    });

    // Create app with factory
    app = await createApp({
      preset: 'development',
      auth: { jwt: { secret: 'test-jwt-secret-must-be-at-least-32-chars-long' } },
      logger: false,
      cors: { origin: true },
      helmet: false, // Disable for testing
      rateLimit: false, // Disable for testing
      plugins: async (fastify) => {
        // Register lifecycle hooks on instance-scoped hook system
        // (Now scoped per app instance instead of global singleton)
        fastify.arc.hooks.before('product', 'create', async (ctx) => {
          // Auto-generate slug from name
          if (ctx.data?.name && !ctx.data.slug) {
            return {
              ...ctx.data,
              slug: ctx.data.name.toLowerCase().replace(/\s+/g, '-'),
            };
          }
        });

        fastify.arc.hooks.after('product', 'create', async (ctx) => {
          // Track created product for testing
          const createdId = ctx.result?._id?.toString() || null;
          console.log(`[E2E Test] Product created: ${createdId}`);
        });

        // Register product resource
        await fastify.register(productResource.toPlugin());
      },
    });

    await app.listen({ port: testPort, host: '127.0.0.1' });
  });

  afterAll(async () => {
    await app.close();
    await teardownTestDatabase();
  });

  describe('Health Endpoints', () => {
    it('should respond to health check', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/_health/live',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);
      expect(payload.status).toBe('ok');
    });

    it('should respond to readiness check', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/_health/ready',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);
      expect(payload.status).toBe('ready');
    });
  });

  describe('CRUD Operations with Hooks', () => {
    let productId: string;

    it('should create a product with beforeCreate hook', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/products',
        payload: {
          name: 'Test Product',
          description: 'A test product',
          price: 99.99,
        },
      });

      expect(response.statusCode).toBe(201);
      const payload = JSON.parse(response.payload);

      expect(payload.success).toBe(true);
      expect(payload.data).toMatchObject({
        name: 'Test Product',
        description: 'A test product',
        price: 99.99,
        slug: 'test-product', // Auto-generated by hook
      });

      productId = payload.data._id;
    });

    it('should list products', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      expect(payload.success).toBe(true);
      // Check if data exists before assertions
      if (payload && payload.data) {
        expect(payload.data.length).toBeGreaterThanOrEqual(1);
        expect(payload.data[0].name).toBe('Test Product');
        // MongoKit returns pagination at top level
        expect(payload.total).toBeGreaterThanOrEqual(1);
      }
    });

    it('should get product by ID', async () => {
      const response = await app.inject({
        method: 'GET',
        url: `/products/${productId}`,
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      expect(payload.success).toBe(true);
      expect(payload.data._id).toBe(productId);
      expect(payload.data.name).toBe('Test Product');
    });

    it('should update a product', async () => {
      const response = await app.inject({
        method: 'PATCH',
        url: `/products/${productId}`,
        payload: {
          price: 149.99,
          description: 'Updated description',
        },
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      expect(payload.success).toBe(true);
      expect(payload.data.price).toBe(149.99);
      expect(payload.data.description).toBe('Updated description');
      expect(payload.data.name).toBe('Test Product'); // Unchanged
    });

    it('should delete a product', async () => {
      const response = await app.inject({
        method: 'DELETE',
        url: `/products/${productId}`,
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      expect(payload.success).toBe(true);

      // Verify deletion
      const getResponse = await app.inject({
        method: 'GET',
        url: `/products/${productId}`,
      });

      expect(getResponse.statusCode).toBe(404);
    });

    it('should return 404 for non-existent product', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products/507f1f77bcf86cd799439011', // Valid but non-existent ID
      });

      expect(response.statusCode).toBe(404);
    });
  });

  describe('Query Features', () => {
    beforeAll(async () => {
      // Create test products
      const ProductModel = mongoose.model('E2EProduct');
      await ProductModel.create([
        { name: 'Cheap Product', price: 10, isActive: true },
        { name: 'Medium Product', price: 50, isActive: true },
        { name: 'Expensive Product', price: 200, isActive: true },
        { name: 'Inactive Product', price: 100, isActive: false },
      ]);
    });

    it('should filter by price range', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products?price[gte]=40&price[lte]=100',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      // MongoKit filters should work
      if (payload && payload.data) {
        const filteredProducts = payload.data.filter((p: any) => p.price >= 40 && p.price <= 100);
        expect(filteredProducts.length).toBeGreaterThanOrEqual(1);
      }
    });

    it('should filter by exact match', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products?isActive=true',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      if (payload && payload.data) {
        expect(payload.data.length).toBeGreaterThanOrEqual(1);
        // All returned products should be active
        const allActive = payload.data.every((p: any) => p.isActive === true);
        expect(allActive).toBe(true);
      }
    });

    it('should sort products', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products?sort=-price&isActive=true',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      if (payload && payload.data && payload.data.length >= 2) {
        const prices = payload.data.map((p: any) => p.price);
        // Should be sorted descending by price
        expect(prices[0]).toBeGreaterThanOrEqual(prices[1]);
      }
    });

    it('should paginate results', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products?page=1&limit=2',
      });

      expect(response.statusCode).toBe(200);
      const payload = JSON.parse(response.payload);

      // MongoKit pagination at top level
      if (payload && payload.data) {
        expect(payload.data.length).toBeLessThanOrEqual(2);
        expect(payload.page).toBe(1);
        expect(payload.limit).toBe(2);
        expect(payload.total).toBeGreaterThanOrEqual(4);
      }
    });
  });

  describe('Error Handling', () => {
    it('should handle validation errors', async () => {
      const response = await app.inject({
        method: 'POST',
        url: '/products',
        payload: {
          // Missing required fields
        },
      });

      // Will succeed because we don't have validation set up
      // In real app, would return 400 with validation errors
      expect(response.statusCode).toBeLessThan(500);
    });

    it('should handle invalid ObjectId', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/products/invalid-id',
      });

      // MongoKit throws error for invalid ObjectId format, resulting in 500
      expect(response.statusCode).toBeGreaterThanOrEqual(400);
    });

    it('should handle server errors gracefully', async () => {
      // Close database connection to force error
      await mongoose.connection.close();

      const response = await app.inject({
        method: 'GET',
        url: '/products',
      });

      expect(response.statusCode).toBe(500);

      // Reconnect for other tests
      await mongoose.connect(mongoUri);
    });
  });

  describe('OpenAPI Documentation', () => {
    it('should expose OpenAPI spec', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/docs/json',
      });

      // Might not be available depending on factory config
      if (response.statusCode === 200) {
        const spec = JSON.parse(response.payload);
        expect(spec.openapi).toBeDefined();
        expect(spec.paths).toBeDefined();
      }
    });
  });
});
