/**
 * Template factory for `arc generate`.
 *
 * `getTemplates(ts, config)` returns a record of per-file template
 * functions. Each closure captures the language flag (`ts`) and project
 * config (multi-tenant, adapter, etc.) so call sites only need to pass
 * the resource-specific `name` / `fileName`. Templates remain pure —
 * no I/O, so the scaffolder's file-writer is the only spot that touches
 * disk.
 *
 * Templates included:
 *   - `model`       Mongoose schema with optional tenant field + index
 *   - `repository`  MongoKit-backed repo (or custom-adapter stub)
 *   - `controller`  BaseController extension scaffold
 *   - `schemas`     `buildCrudSchemasFromModel` with the field-rule menu
 *   - `resource`    `defineResource` wiring — branches on multi-tenant
 *   - `mcp`         Custom MCP tool examples (defineTool + zod schemas)
 *   - `test`        Vitest spec using `createTestApp` + `expectArc`
 */

import { pluralize } from "../../../utils/pluralize.js";
import { toCamelCase } from "./name-helpers.js";
import type { ArcProjectConfig } from "./types.js";

/**
 * Template functions accept:
 * - `name`: PascalCase class name (e.g. `OrgProfile`)
 * - `fileName`: kebab-case for file paths (e.g. `org-profile`)
 */
export function getTemplates(ts: boolean, config: ArcProjectConfig = {}) {
  const isMultiTenant = config.tenant === "multi";

  return {
    model: (name: string, _fileName: string) => {
      const camel = toCamelCase(name);
      const mongooseImport = ts
        ? "import mongoose, { type HydratedDocument, type Model, type Types } from 'mongoose';"
        : "import mongoose from 'mongoose';";
      const docInterface = ts
        ? [
            "",
            "/**",
            " * Persisted shape — what `.lean()` and `.toObject()` return. Carrying this",
            ` * through \`Model<I${name}>\` lets \`.select(...)\` / \`.find(...)\` / \`.lean()\``,
            " * infer correctly so domain methods don't need `as` casts.",
            " *",
            " * Replace the placeholder fields with your real domain shape.",
            " */",
            `export interface I${name} {`,
            "  _id: Types.ObjectId;",
            ...(isMultiTenant ? ["  organizationId: Types.ObjectId;"] : []),
            "  // TODO: define your fields here",
            "  createdAt: Date;",
            "  updatedAt: Date;",
            "}",
            "",
            `export type ${name}Document = HydratedDocument<I${name}>;`,
            "",
          ].join("\n")
        : "";
      const schemaGeneric = ts ? `<I${name}>` : "";
      const tenantField = isMultiTenant
        ? "    organizationId: { type: Schema.Types.ObjectId, required: true, index: true },\n"
        : "";
      const tenantIndex = isMultiTenant
        ? `${camel}Schema.index({ organizationId: 1, createdAt: -1 });\n`
        : "";
      const modelDecl = ts
        ? [
            `const ${name}: Model<I${name}> =`,
            `  (mongoose.models.${name} as Model<I${name}> | undefined) ??`,
            `  mongoose.model<I${name}>('${name}', ${camel}Schema);`,
          ].join("\n")
        : `const ${name} = mongoose.models.${name} || mongoose.model('${name}', ${camel}Schema);`;

      return `/**
 * ${name} Model
 * Generated by Arc CLI
 */

${mongooseImport}

const { Schema } = mongoose;
${docInterface}
const ${camel}Schema = new Schema${schemaGeneric}(
  {
${tenantField}    // TODO: declare your fields here, e.g. name: { type: String, required: true, trim: true },
  },
  { timestamps: true }
);

${tenantIndex}${modelDecl}

export default ${name};
`;
    },

    repository: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      const useMongoKit = config.adapter === "mongokit" || !config.adapter;

      // Custom-adapter projects don't have mongokit installed — emit a
      // stub repository pointing at the project's own kit. The user
      // wires it up to whatever they're using (sqlitekit, prismakit,
      // a hand-rolled MinimalRepo).
      if (!useMongoKit) {
        const generic = ts ? `<I${name}>` : "";
        const typeImport = ts ? `\nimport type { I${name} } from './${fileName}.model.js';` : "";
        return `/**
 * ${name} Repository
 * Generated by Arc CLI
 *
 * This project uses a custom adapter — wire your repository to whichever
 * kit you're using (sqlitekit, prismakit, custom). Replace the body below
 * with your kit's Repository constructor. Arc only requires the
 * \`MinimalRepo\` floor (getAll/getById/create/update/delete) declared in
 * \`@classytic/repo-core/repository\`.
 */
${typeImport}

// Replace with your kit's repository instance:
//   import { Repository } from '@classytic/sqlitekit';
//   const ${camel}Repository = new Repository${generic}(${name}Table);
//   export default ${camel}Repository;

const ${camel}Repository = {
  // TODO: implement MinimalRepo<${ts ? `I${name}` : "any"}>
} as never;

export default ${camel}Repository;
`;
      }

      const generic = ts ? `<I${name}>` : "";
      const typeImport = ts ? `\nimport type { I${name} } from './${fileName}.model.js';` : "";
      return `/**
 * ${name} Repository
 * Generated by Arc CLI
 */

import {
  Repository,
  methodRegistryPlugin,
  softDeletePlugin,
} from '@classytic/mongokit';
import ${name} from './${fileName}.model.js';${typeImport}

class ${name}Repository extends Repository${generic} {
  constructor() {
    super(${name}, [methodRegistryPlugin(), softDeletePlugin()]);
  }

  // Add domain methods here. arc + mongokit ship the standard CRUD
  // (getAll/getById/create/update/delete) on the base class, so only
  // write a method when there's real domain logic to capture.
}

const ${camel}Repository = new ${name}Repository();
export default ${camel}Repository;
export { ${name}Repository };
`;
    },

    controller: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} Controller
 * Generated by Arc CLI
 *
 * Note: defineResource() auto-creates a controller from the adapter.
 * Only create a custom controller when you need custom methods.
 */

import { BaseController } from '@classytic/arc';
import ${camel}Repository from './${fileName}.repository.js';

class ${name}Controller extends BaseController {
  constructor() {
    super(${camel}Repository, {
      resourceName: '${fileName}',
    });
  }

  // Add custom controller methods here
}

const ${camel}Controller = new ${name}Controller();
export default ${camel}Controller;
`;
    },

    schemas: (name: string, fileName: string) => `/**
 * ${name} Schemas
 * Generated by Arc CLI
 */

import ${name} from './${fileName}.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit';

/**
 * CRUD Schemas with Field Rules
 */
const crudSchemas = buildCrudSchemasFromModel(${name}, {
  strictAdditionalProperties: true,
  fieldRules: {
    // systemManaged: framework stamps it — strip from body + required[]
    // deletedAt: { systemManaged: true },
    // immutable: cannot be updated after creation
    // slug: { immutable: true },
    // immutableAfterCreate: alias for immutable
    // organizationId: { immutableAfterCreate: true },
    // optional: removed from required[] (properties kept)
    // description: { optional: true },
    // nullable: widen JSON-Schema type to accept null (Zod .nullable() rescue)
    // priceMode: { nullable: true },
    // preserveForElevated: elevated admins keep the field on ingest (cross-tenant writes)
    // organizationId: { systemManaged: true, preserveForElevated: true },
  },
  query: {
    // Add your filterable fields here. createdAt is the default so the
    // generated routes accept ?createdAt[gte]=2026-01-01 with no extra
    // wiring. Add domain fields below as your model grows.
    filterableFields: {
      createdAt: 'date',
    },
  },
});

export default crudSchemas;
`,

    resource: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      const useMongoKit = config.adapter === "mongokit" || !config.adapter;
      // arc 2.12+ no longer ships a built-in mongoose-schema fallback —
      // OpenAPI generation requires a `schemaGenerator`. mongokit's
      // `buildCrudSchemasFromModel` is the canonical wiring.
      const schemaGeneratorImport = useMongoKit
        ? `import { buildCrudSchemasFromModel } from '@classytic/mongokit';\n`
        : "";
      const queryParserImport = useMongoKit
        ? `\nimport { QueryParser } from '@classytic/mongokit';\n\n// Fail-closed by default (mongokit >=3.25): invalid/blocked query input →\n// HTTP 400 instead of silently broadening the result set.\nconst queryParser = new QueryParser({\n  // Whitelist the fields this resource accepts in URL filters.\n  // Empty by default — only \`createdAt\` is implicit; add yours.\n  allowedFilterFields: [],\n});\n`
        : "";
      const adapterCall = useMongoKit
        ? `createMongooseAdapter({ model: ${name}, repository: ${camel}Repository, schemaGenerator: buildCrudSchemasFromModel })`
        : `createMongooseAdapter({ model: ${name}, repository: ${camel}Repository })`;
      const queryParserConfig = useMongoKit ? `\n  queryParser,` : "";

      return isMultiTenant
        ? `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource } from '@classytic/arc';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { allOf, requireOrgMembership, requireRoles } from '@classytic/arc/permissions';
import { multiTenantPreset } from '@classytic/arc/presets';
${schemaGeneratorImport}import ${name}${ts ? `, { type I${name} }` : ""} from './${fileName}.model.js';
import ${camel}Repository from './${fileName}.repository.js';${queryParserImport}

const ${camel}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${fileName}',
  adapter: ${adapterCall},${queryParserConfig}

  // Multi-tenant default: scope reads/writes by \`organizationId\`. For
  // company-wide tables (lookup data, platform settings) set
  // \`tenantField: false\` instead — otherwise queries silently return
  // nothing because the column doesn't exist.
  //
  // Multi-level tenancy (org + branch + project, etc.) — replace with:
  //   multiTenantPreset({ tenantFields: [
  //     { field: 'organizationId', type: 'org' },
  //     { field: 'branchId', contextKey: 'branchId' },
  //   ] })
  presets: ['softDelete', multiTenantPreset({ tenantField: 'organizationId' })],

  // Tenant-cleanup strategy. Runs when an organization is deleted —
  // wire \`cascadeDeleteForOrganization(arc.registry, { organizationId })\`
  // into your auth lifecycle (Better Auth's afterDeleteOrganization,
  // billing webhook, etc.) and every flagged resource is cleaned in one
  // pass. Strategies: 'hard' (delete), 'soft' (deletedAt), 'anonymize'
  // (clear PII, keep row — for legal-retained ledgers), 'skip' (no-op
  // with mandatory reason). See arc/docs/compliance/tenant-cleanup.md.
  onTenantDelete: { strategy: { type: 'hard' } },

  // 2.16 — declarative CRUD allow-list (positive form). Uncomment to
  // restrict the surface; a future arc CRUD op won't silently leak in
  // because every op is opt-in. Mutually exclusive with \`disabledRoutes\`.
  //   crud: { list: true, get: true },

  permissions: {
    list: requireOrgMembership(),
    get: requireOrgMembership(),
    create: allOf(requireOrgMembership(), requireRoles(['admin'])),
    update: allOf(requireOrgMembership(), requireRoles(['admin'])),
    delete: allOf(requireOrgMembership(), requireRoles(['admin'])),
  },

  // 2.16 — typed state-transition actions. \`defineAction()\` captures the
  // schema's literal type so \`data\` is inferred — no \`as MyShape\` casts.
  // Set \`id: false\` for resource-root actions (propose / search / bulk).
  //
  //   import { defineAction } from '@classytic/arc';
  //   import { z } from 'zod';
  //
  //   actions: {
  //     approve: defineAction({
  //       schema: z.object({ reviewedBy: z.string() }),
  //       permissions: requireRoles(['admin']),
  //       handler: async (id, data) => { /* data.reviewedBy is typed */ },
  //     }),
  //   },
});

export default ${camel}Resource;
`
        : `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource } from '@classytic/arc';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
${schemaGeneratorImport}import ${name}${ts ? `, { type I${name} }` : ""} from './${fileName}.model.js';
import ${camel}Repository from './${fileName}.repository.js';${queryParserImport}

const ${camel}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${fileName}',
  adapter: ${adapterCall},${queryParserConfig}

  // Single-tenant default: arc auto-infers \`tenantField: false\` when
  // the model has no \`organizationId\` path (silent-zero-results
  // footgun closed in 2.12). Set \`tenantField: '<field>'\` to opt INTO
  // tenant scoping, or \`tenantField: false\` to make it explicit.
  presets: ['softDelete'],

  // 2.16 — declarative CRUD allow-list (positive form). Uncomment to
  // restrict the surface; a future arc CRUD op won't silently leak in
  // because every op is opt-in. Mutually exclusive with \`disabledRoutes\`.
  //   crud: { list: true, get: true },

  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireRoles(['admin']),
    update: requireRoles(['admin']),
    delete: requireRoles(['admin']),
  },

  // 2.16 — typed state-transition actions. \`defineAction()\` captures the
  // schema's literal type so \`data\` is inferred. Set \`id: false\` for
  // resource-root actions (propose / search / bulk).
  //
  //   import { defineAction } from '@classytic/arc';
  //   import { z } from 'zod';
  //
  //   actions: {
  //     publish: defineAction({
  //       schema: z.object({ scheduledFor: z.string().datetime().optional() }),
  //       permissions: requireRoles(['admin']),
  //       handler: async (id, data) => { /* data.scheduledFor is typed */ },
  //     }),
  //   },
});

export default ${camel}Resource;
`;
    },

    mcp: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} MCP Tools
 * Generated by Arc CLI
 *
 * Custom MCP tools for the ${name} domain.
 * CRUD tools (list/get/create/update/delete) are auto-generated by mcpPlugin.
 * Add domain-specific tools here (actions, analytics, workflows).
 */

import { defineTool } from '@classytic/arc/mcp';
${ts ? "import { z } from 'zod';\n" : "const { z } = require('zod');\n"}
// Example: domain-specific action tool
// export const activate${name}Tool = defineTool('activate_${fileName}', {
//   description: 'Activate a ${name.toLowerCase()} by ID',
//   input: { id: z.string().describe('${name} ID') },
//   annotations: { destructiveHint: true, idempotentHint: true },
//   handler: async ({ id }, ctx) => {
//     // Your logic here
//     return { content: [{ type: 'text', text: \`Activated ${name.toLowerCase()} \${id}\` }] };
//   },
// });

// Example: read-only analytics tool
// export const ${camel}StatsTool = defineTool('${fileName}_stats', {
//   description: 'Get ${name.toLowerCase()} statistics',
//   input: { period: z.enum(['7d', '30d', '90d']).optional() },
//   annotations: { readOnlyHint: true },
//   handler: async ({ period }) => {
//     // Your logic here
//     return { content: [{ type: 'text', text: JSON.stringify({ total: 0, period }) }] };
//   },
// });
`;
    },

    test: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} Tests
 * Generated by Arc CLI
 *
 * Testing surface (arc 2.12+):
 *   - createTestApp   turnkey Fastify + in-memory Mongo + auth + fixtures
 *   - expectArc       fluent matchers — .ok / .failed / .unauthorized /
 *                     .forbidden / .notFound / .conflict / .validationError /
 *                     .paginated / .hidesField / .hasData / .hasStatus
 *   - ctx.auth        unified TestAuthProvider — register a role, reuse .headers
 *
 * Wire shape (post-2.12): single-doc responses are flat (\`{_id, name, ...}\`),
 * paginated responses are \`{ method: 'offset', data: [...], page, ... }\`.
 * No \`success\` envelope — HTTP status discriminates success vs error;
 * errors carry the canonical ErrorContract \`{ code, message, status }\`.
 */

import { describe, it, beforeAll, afterAll, expect } from 'vitest';
import { createTestApp, expectArc } from '@classytic/arc/testing';
import type { TestAppContext } from '@classytic/arc/testing';
import ${camel}Resource from '../src/resources/${fileName}/${fileName}.resource.js';

describe('${name} Resource', () => {
  let ctx${ts ? ": TestAppContext" : ""};

  beforeAll(async () => {
    ctx = await createTestApp({
      resources: [${camel}Resource],
      authMode: 'jwt',
      connectMongoose: true,
    });

    ctx.auth${ts ? "!" : ""}.register('admin', {
      user: { id: '1', roles: ['admin'] },
      orgId: 'org-1',
    });
  });

  afterAll(() => ctx.close());

  describe('GET /${pluralize(fileName)}', () => {
    it('returns a paginated list', async () => {
      const res = await ctx.app.inject({
        method: 'GET',
        url: '/${pluralize(fileName)}',
        headers: ctx.auth${ts ? "!" : ""}.as('admin').headers,
      });
      expectArc(res).ok().paginated();
    });

    it('rejects unauthenticated requests', async () => {
      const res = await ctx.app.inject({ method: 'GET', url: '/${pluralize(fileName)}' });
      expectArc(res).unauthorized();
    });
  });

  describe('POST /${pluralize(fileName)}', () => {
    it('creates a record (flat wire shape — no envelope)', async () => {
      const res = await ctx.app.inject({
        method: 'POST',
        url: '/${pluralize(fileName)}',
        headers: ctx.auth${ts ? "!" : ""}.as('admin').headers,
        payload: { name: 'Example' },
      });
      expectArc(res).ok(201);
      // Single-doc response is flat: \`body._id\` (not \`body.data._id\`).
      const body = res.json()${ts ? " as { _id: string; name: string }" : ""};
      expect(body._id).toBeDefined();
      expect(body.name).toBe('Example');
    });
  });

  // More patterns to extend:
  //   - expectArc(res).forbidden() / .notFound() / .validationError()
  //   - expectArc(res).hidesField('password') for field-level perms
  //   - ctx.fixtures.create('${fileName}', {...}) for seeded data
  //   - error wire shape: body.code === 'arc.not_found' (ErrorContract)
});
`;
    },
  };
}

export type GenerateTemplates = ReturnType<typeof getTemplates>;
