/**
 * Arc CLI - Generate Command
 *
 * Scaffolds resources with consistent naming:
 * - src/resources/product/product.model.ts
 * - src/resources/product/product.repository.ts
 * - src/resources/product/product.resource.ts
 * - src/resources/product/product.controller.ts
 * - src/resources/product/product.schemas.ts
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Check if TypeScript project
function isTypeScriptProject(): boolean {
  return existsSync(join(process.cwd(), 'tsconfig.json'));
}

// Templates
function getTemplates(ts: boolean) {
  const ext = ts ? 'ts' : 'js';

  return {
    model: (name: string) => `/**
 * ${name} Model
 * Generated by Arc CLI
 */

import mongoose${ts ? ', { type HydratedDocument }' : ''} from 'mongoose';

const { Schema } = mongoose;
${ts ? `
type ${name} = {
  name: string;
  description?: string;
  isActive: boolean;
};

export type ${name}Document = HydratedDocument<${name}>;
` : ''}
const ${name.toLowerCase()}Schema = new Schema${ts ? `<${name}>` : ''}(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

// Indexes
${name.toLowerCase()}Schema.index({ name: 1 });
${name.toLowerCase()}Schema.index({ isActive: 1 });

const ${name} = mongoose.models.${name}${ts ? ` as mongoose.Model<${name}>` : ''} || mongoose.model${ts ? `<${name}>` : ''}('${name}', ${name.toLowerCase()}Schema);
export default ${name};
`,

    repository: (name: string) => `/**
 * ${name} Repository
 * Generated by Arc CLI
 */

import {
  Repository,
  methodRegistryPlugin,
  softDeletePlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
${ts ? `import type { ${name}Document } from './${name.toLowerCase()}.model.js';` : ''}
import ${name} from './${name.toLowerCase()}.model.js';

class ${name}Repository extends Repository${ts ? `<${name}Document>` : ''} {
  constructor() {
    super(${name}${ts ? ' as any' : ''}, [
      methodRegistryPlugin(),
      softDeletePlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find all active records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }

  // Add custom repository methods here
}

const ${name.toLowerCase()}Repository = new ${name}Repository();
export default ${name.toLowerCase()}Repository;
export { ${name}Repository };
`,

    controller: (name: string) => `/**
 * ${name} Controller
 * Generated by Arc CLI
 */

import { BaseController } from '@classytic/arc';
import ${name.toLowerCase()}Repository from './${name.toLowerCase()}.repository.js';
import { ${name.toLowerCase()}SchemaOptions } from './${name.toLowerCase()}.schemas.js';

class ${name}Controller extends BaseController {
  constructor() {
    super(${name.toLowerCase()}Repository${ts ? ' as any' : ''}, { schemaOptions: ${name.toLowerCase()}SchemaOptions });
  }

  // Add custom controller methods here
}

const ${name.toLowerCase()}Controller = new ${name}Controller();
export default ${name.toLowerCase()}Controller;
`,

    schemas: (name: string) => `/**
 * ${name} Schemas
 * Generated by Arc CLI
 */

import ${name} from './${name.toLowerCase()}.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 */
const crudSchemas = buildCrudSchemasFromModel(${name}, {
  strictAdditionalProperties: true,
  fieldRules: {
    // Mark fields as system-managed (excluded from create/update)
    // deletedAt: { systemManaged: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
});

// Schema options for controller
export const ${name.toLowerCase()}SchemaOptions${ts ? ': any' : ''} = {
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
};

export default crudSchemas;
`,

    resource: (name: string) => `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource } from '@classytic/arc';
import { createAdapter } from '#shared/adapter.js';
import { publicReadPermissions } from '#shared/permissions.js';
import ${name} from './${name.toLowerCase()}.model.js';
import ${name.toLowerCase()}Repository from './${name.toLowerCase()}.repository.js';
import ${name.toLowerCase()}Controller from './${name.toLowerCase()}.controller.js';

const ${name.toLowerCase()}Resource = defineResource({
  name: '${name.toLowerCase()}',
  displayName: '${name}s',
  prefix: '/${name.toLowerCase()}s',

  adapter: createAdapter(${name}, ${name.toLowerCase()}Repository),
  controller: ${name.toLowerCase()}Controller,

  presets: ['softDelete'],

  permissions: publicReadPermissions,

  // Add custom routes here:
  // additionalRoutes: [
  //   {
  //     method: 'GET',
  //     path: '/custom',
  //     summary: 'Custom endpoint',
  //     handler: async (request, reply) => { ... },
  //   },
  // ],
});

export default ${name.toLowerCase()}Resource;
`,

    test: (name: string) => `/**
 * ${name} Tests
 * Generated by Arc CLI
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createAppInstance } from '../src/app.js';
${ts ? "import type { FastifyInstance } from 'fastify';\n" : ''}
describe('${name} Resource', () => {
  let app${ts ? ': FastifyInstance' : ''};

  beforeAll(async () => {
    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/test-${name.toLowerCase()}';
    await mongoose.connect(testDbUri);
    app = await createAppInstance();
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await mongoose.connection.close();
  });

  describe('GET /${name.toLowerCase()}s', () => {
    it('should return a list', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/${name.toLowerCase()}s',
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('docs');
    });
  });
});
`,
  };
}

/**
 * Generate command handler
 */
export async function generate(type: string | undefined, args: string[]): Promise<void> {
  if (!type) {
    console.error('Error: Missing type argument');
    console.log('Usage: arc generate <resource|controller|model|repository|schemas> <name>');
    process.exit(1);
  }

  const [name] = args;
  if (!name) {
    console.error('Error: Missing name argument');
    console.log('Usage: arc generate <type> <name>');
    console.log('Example: arc generate resource product');
    process.exit(1);
  }

  // Capitalize first letter
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  const lowerName = name.toLowerCase();

  // Detect TypeScript
  const ts = isTypeScriptProject();
  const ext = ts ? 'ts' : 'js';
  const templates = getTemplates(ts);

  // Resource path: src/resources/<name>/
  const resourcePath = join(process.cwd(), 'src', 'resources', lowerName);

  switch (type) {
    case 'resource':
    case 'r':
      await generateResource(capitalizedName, lowerName, resourcePath, templates, ext);
      break;

    case 'controller':
    case 'c':
      await generateFile(capitalizedName, lowerName, resourcePath, 'controller', templates.controller, ext);
      break;

    case 'model':
    case 'm':
      await generateFile(capitalizedName, lowerName, resourcePath, 'model', templates.model, ext);
      break;

    case 'repository':
    case 'repo':
      await generateFile(capitalizedName, lowerName, resourcePath, 'repository', templates.repository, ext);
      break;

    case 'schemas':
    case 's':
      await generateFile(capitalizedName, lowerName, resourcePath, 'schemas', templates.schemas, ext);
      break;

    default:
      console.error(`Unknown type: ${type}`);
      console.log('Available types: resource, controller, model, repository, schemas');
      process.exit(1);
  }
}

/**
 * Generate a full resource
 */
async function generateResource(
  name: string,
  lowerName: string,
  resourcePath: string,
  templates: ReturnType<typeof getTemplates>,
  ext: string
): Promise<void> {
  console.log(`\n📦 Generating resource: ${name}...\n`);

  // Create directory
  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  📁 Created: src/resources/${lowerName}/`);
  }

  // Generate files
  const files: Record<string, string> = {
    [`${lowerName}.model.${ext}`]: templates.model(name),
    [`${lowerName}.repository.${ext}`]: templates.repository(name),
    [`${lowerName}.controller.${ext}`]: templates.controller(name),
    [`${lowerName}.schemas.${ext}`]: templates.schemas(name),
    [`${lowerName}.resource.${ext}`]: templates.resource(name),
  };

  for (const [filename, content] of Object.entries(files)) {
    const filepath = join(resourcePath, filename);
    if (existsSync(filepath)) {
      console.warn(`  ⚠  Skipped: ${filename} (already exists)`);
    } else {
      writeFileSync(filepath, content);
      console.log(`  ✅ Created: ${filename}`);
    }
  }

  // Generate test file
  const testsDir = join(process.cwd(), 'tests');
  if (!existsSync(testsDir)) {
    mkdirSync(testsDir, { recursive: true });
  }
  const testPath = join(testsDir, `${lowerName}.test.${ext}`);
  if (!existsSync(testPath)) {
    writeFileSync(testPath, templates.test(name));
    console.log(`  ✅ Created: tests/${lowerName}.test.${ext}`);
  }

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                    ✅ Resource Generated!                     ║
╚═══════════════════════════════════════════════════════════════╝

Next steps:

1. Register in src/resources/index.${ext}:
   import ${lowerName}Resource from './${lowerName}/${lowerName}.resource.js';

   export const resources = [
     // ... existing resources
     ${lowerName}Resource,
   ];

2. Customize the model schema in:
   src/resources/${lowerName}/${lowerName}.model.${ext}

3. Run tests:
   npm test
`);
}

/**
 * Generate a single file
 */
async function generateFile(
  name: string,
  lowerName: string,
  resourcePath: string,
  fileType: string,
  template: (name: string) => string,
  ext: string
): Promise<void> {
  console.log(`\n📦 Generating ${fileType}: ${name}...\n`);

  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  📁 Created: src/resources/${lowerName}/`);
  }

  const filename = `${lowerName}.${fileType}.${ext}`;
  const filepath = join(resourcePath, filename);

  if (existsSync(filepath)) {
    console.error(`  ❌ Error: ${filename} already exists`);
    process.exit(1);
  }

  writeFileSync(filepath, template(name));
  console.log(`  ✅ Created: ${filename}`);
}

export default generate;
