/**
 * Arc CLI - Generate Command
 *
 * Scaffolds resources with consistent naming:
 * - src/resources/product/product.model.ts
 * - src/resources/product/product.repository.ts
 * - src/resources/product/product.resource.ts
 * - src/resources/product/product.controller.ts
 * - src/resources/product/product.schemas.ts
 *
 * Handles kebab-case names: `arc g r org-profile` generates:
 * - Class names: OrgProfile, OrgProfileRepository
 * - Variable names: orgProfileSchema, orgProfileRepository
 * - File names: org-profile.model.ts, org-profile.repository.ts
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pluralize } from "../utils/pluralize.js";

interface ArcProjectConfig {
  adapter?: "mongokit" | "custom";
  auth?: "jwt" | "better-auth";
  tenant?: "multi" | "single";
  typescript?: boolean;
  mcp?: boolean;
}

// Read .arcrc project config (written by `arc init`)
function readProjectConfig(): ArcProjectConfig {
  try {
    const rcPath = join(process.cwd(), ".arcrc");
    return JSON.parse(readFileSync(rcPath, "utf-8"));
  } catch {
    return {};
  }
}

// Check if TypeScript project
function isTypeScriptProject(): boolean {
  return existsSync(join(process.cwd(), "tsconfig.json"));
}

// ============================================================================
// Name Helpers
// ============================================================================

/** Convert kebab-case to PascalCase: org-profile → OrgProfile */
function toPascalCase(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Convert PascalCase to camelCase: OrgProfile → orgProfile */
function toCamelCase(pascalName: string): string {
  return pascalName.charAt(0).toLowerCase() + pascalName.slice(1);
}

// ============================================================================
// Templates
// ============================================================================

/**
 * Template functions accept:
 * - name: PascalCase class name (e.g., OrgProfile)
 * - fileName: kebab-case for file paths (e.g., org-profile)
 */
function getTemplates(ts: boolean, config: ArcProjectConfig = {}) {
  const isMultiTenant = config.tenant === "multi";

  return {
    model: (name: string, _fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} Model
 * Generated by Arc CLI
 */

import mongoose${ts ? ", { type HydratedDocument }" : ""} from 'mongoose';

const { Schema } = mongoose;
${
  ts
    ? `
export interface I${name} {
  name: string;
  description?: string;
  isActive: boolean;
}

export type ${name}Document = HydratedDocument<I${name}>;
`
    : ""
}
const ${camel}Schema = new Schema${ts ? `<I${name}>` : ""}(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

// Indexes
${camel}Schema.index({ name: 1 });
${camel}Schema.index({ isActive: 1 });

const ${name} = mongoose.models.${name} || mongoose.model('${name}', ${camel}Schema);
export default ${name};
`;
    },

    repository: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      const generic = ts ? `<I${name}>` : "";
      const typeImport = ts ? `\nimport type { I${name} } from './${fileName}.model.js';` : "";
      return `/**
 * ${name} Repository
 * Generated by Arc CLI
 */

import {
  Repository,
  methodRegistryPlugin,
  softDeletePlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
import ${name} from './${fileName}.model.js';${typeImport}

class ${name}Repository extends Repository${generic} {
  constructor() {
    super(${name}, [
      methodRegistryPlugin(),
      softDeletePlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find all active records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }
}

const ${camel}Repository = new ${name}Repository();
export default ${camel}Repository;
export { ${name}Repository };
`;
    },

    controller: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} Controller
 * Generated by Arc CLI
 *
 * Note: defineResource() auto-creates a controller from the adapter.
 * Only create a custom controller when you need custom methods.
 */

import { BaseController } from '@classytic/arc';
import ${camel}Repository from './${fileName}.repository.js';

class ${name}Controller extends BaseController {
  constructor() {
    super(${camel}Repository, {
      resourceName: '${fileName}',
    });
  }

  // Add custom controller methods here
}

const ${camel}Controller = new ${name}Controller();
export default ${camel}Controller;
`;
    },

    schemas: (name: string, fileName: string) => `/**
 * ${name} Schemas
 * Generated by Arc CLI
 */

import ${name} from './${fileName}.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 */
const crudSchemas = buildCrudSchemasFromModel(${name}, {
  strictAdditionalProperties: true,
  fieldRules: {
    // systemManaged: framework stamps it — strip from body + required[]
    // deletedAt: { systemManaged: true },
    // immutable: cannot be updated after creation
    // slug: { immutable: true },
    // immutableAfterCreate: alias for immutable
    // organizationId: { immutableAfterCreate: true },
    // optional: removed from required[] (properties kept)
    // description: { optional: true },
    // nullable: widen JSON-Schema type to accept null (Zod .nullable() rescue)
    // priceMode: { nullable: true },
    // preserveForElevated: elevated admins keep the field on ingest (cross-tenant writes)
    // organizationId: { systemManaged: true, preserveForElevated: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
});

export default crudSchemas;
`,

    resource: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      const useMongoKit = config.adapter === "mongokit" || !config.adapter;
      const queryParserImport = useMongoKit
        ? `\nimport { QueryParser } from '@classytic/mongokit';\n\nconst queryParser = new QueryParser({\n  allowedFilterFields: ['isActive'],\n});\n`
        : "";
      const queryParserConfig = useMongoKit ? `\n  queryParser,` : "";

      return isMultiTenant
        ? `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource, createMongooseAdapter } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import ${name}${ts ? `, { type I${name} }` : ""} from './${fileName}.model.js';
import ${camel}Repository from './${fileName}.repository.js';${queryParserImport}

const ${camel}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${fileName}',
  adapter: createMongooseAdapter({ model: ${name}, repository: ${camel}Repository }),${queryParserConfig}
  presets: ['softDelete'],
  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireRoles(['admin']),
    update: requireRoles(['admin']),
    delete: requireRoles(['admin']),
  },
});

export default ${camel}Resource;
`
        : `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource, createMongooseAdapter } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import ${name}${ts ? `, { type I${name} }` : ""} from './${fileName}.model.js';
import ${camel}Repository from './${fileName}.repository.js';${queryParserImport}

const ${camel}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${fileName}',
  adapter: createMongooseAdapter({ model: ${name}, repository: ${camel}Repository }),${queryParserConfig}
  presets: ['softDelete'],
  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireRoles(['admin']),
    update: requireRoles(['admin']),
    delete: requireRoles(['admin']),
  },
});

export default ${camel}Resource;
`;
    },

    mcp: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} MCP Tools
 * Generated by Arc CLI
 *
 * Custom MCP tools for the ${name} domain.
 * CRUD tools (list/get/create/update/delete) are auto-generated by mcpPlugin.
 * Add domain-specific tools here (actions, analytics, workflows).
 */

import { defineTool } from '@classytic/arc/mcp';
${ts ? "import { z } from 'zod';\n" : "const { z } = require('zod');\n"}
// Example: domain-specific action tool
// export const activate${name}Tool = defineTool('activate_${fileName}', {
//   description: 'Activate a ${name.toLowerCase()} by ID',
//   input: { id: z.string().describe('${name} ID') },
//   annotations: { destructiveHint: true, idempotentHint: true },
//   handler: async ({ id }, ctx) => {
//     // Your logic here
//     return { content: [{ type: 'text', text: \`Activated ${name.toLowerCase()} \${id}\` }] };
//   },
// });

// Example: read-only analytics tool
// export const ${camel}StatsTool = defineTool('${fileName}_stats', {
//   description: 'Get ${name.toLowerCase()} statistics',
//   input: { period: z.enum(['7d', '30d', '90d']).optional() },
//   annotations: { readOnlyHint: true },
//   handler: async ({ period }) => {
//     // Your logic here
//     return { content: [{ type: 'text', text: JSON.stringify({ total: 0, period }) }] };
//   },
// });
`;
    },

    test: (name: string, fileName: string) => {
      const camel = toCamelCase(name);
      return `/**
 * ${name} Tests
 * Generated by Arc CLI
 *
 * 2.11 testing surface:
 *   - createTestApp   turnkey Fastify + in-memory Mongo + auth + fixtures
 *   - expectArc       fluent envelope matchers (.ok, .unauthorized, .forbidden, ...)
 *   - ctx.auth        unified TestAuthProvider — register a role, reuse .headers
 */

import { describe, it, beforeAll, afterAll } from 'vitest';
import { createTestApp, expectArc } from '@classytic/arc/testing';
import type { TestAppContext } from '@classytic/arc/testing';
import ${camel}Resource from '../src/resources/${fileName}/${fileName}.resource.js';

describe('${name} Resource', () => {
  let ctx${ts ? ": TestAppContext" : ""};

  beforeAll(async () => {
    ctx = await createTestApp({
      resources: [${camel}Resource],
      authMode: 'jwt',
      connectMongoose: true,
    });

    ctx.auth${ts ? "!" : ""}.register('admin', {
      user: { id: '1', roles: ['admin'] },
      orgId: 'org-1',
    });
  });

  afterAll(() => ctx.close());

  describe('GET /${pluralize(fileName)}', () => {
    it('should return a paginated list', async () => {
      const res = await ctx.app.inject({ method: 'GET', url: '/${pluralize(fileName)}' });
      expectArc(res).ok().paginated();
    });
  });

  // More coverage patterns:
  //   - expectArc(res).unauthorized() for missing auth
  //   - expectArc(res).forbidden() for wrong role
  //   - ctx.auth.as('admin').headers for authenticated requests
  //   - ctx.fixtures.create('${fileName}', {...}) for seeded data
});
`;
    },
  };
}

/**
 * Generate command handler
 */
export async function generate(type: string | undefined, args: string[]): Promise<void> {
  if (!type) {
    throw new Error(
      "Missing type argument\nUsage: arc generate <resource|controller|model|repository|schemas> <name>",
    );
  }

  const [name, ...restArgs] = args;
  if (!name) {
    throw new Error(
      "Missing name argument\nUsage: arc generate <type> <name>\nExample: arc generate resource product",
    );
  }

  // Convert kebab-case to PascalCase (e.g., org-profile → OrgProfile)
  const capitalizedName = toPascalCase(name);
  // Keep original kebab-case for file names (e.g., org-profile)
  const lowerName = name.toLowerCase();

  // Detect project config
  const projectConfig = readProjectConfig();
  const ts = projectConfig.typescript ?? isTypeScriptProject();
  const ext = ts ? "ts" : "js";
  const templates = getTemplates(ts, projectConfig);

  // Resource path: src/resources/<name>/
  const resourcePath = join(process.cwd(), "src", "resources", lowerName);

  switch (type) {
    case "resource":
    case "r": {
      const includeMcp = projectConfig.mcp === true || restArgs.includes("--mcp");
      await generateResource(capitalizedName, lowerName, resourcePath, templates, ext, includeMcp);
      break;
    }

    case "controller":
    case "c":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "controller",
        templates.controller,
        ext,
      );
      break;

    case "model":
    case "m":
      await generateFile(capitalizedName, lowerName, resourcePath, "model", templates.model, ext);
      break;

    case "repository":
    case "repo":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "repository",
        templates.repository,
        ext,
      );
      break;

    case "schemas":
    case "s":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "schemas",
        templates.schemas,
        ext,
      );
      break;

    case "mcp":
      await generateFile(capitalizedName, lowerName, resourcePath, "mcp", templates.mcp, ext);
      break;

    default:
      throw new Error(
        `Unknown type: ${type}\nAvailable types: resource, controller, model, repository, schemas, mcp`,
      );
  }
}

/**
 * Generate a full resource
 */
async function generateResource(
  name: string,
  lowerName: string,
  resourcePath: string,
  templates: ReturnType<typeof getTemplates>,
  ext: string,
  includeMcp = false,
): Promise<void> {
  console.log(`\nGenerating resource: ${name}...\n`);

  // Create directory
  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  + Created: src/resources/${lowerName}/`);
  }

  // Generate files (defineResource() auto-creates controller, no schemas needed)
  const files: Record<string, string> = {
    [`${lowerName}.model.${ext}`]: templates.model(name, lowerName),
    [`${lowerName}.repository.${ext}`]: templates.repository(name, lowerName),
    [`${lowerName}.resource.${ext}`]: templates.resource(name, lowerName),
  };

  // Include MCP tools file if project uses MCP or --mcp flag passed
  if (includeMcp) {
    files[`${lowerName}.mcp.${ext}`] = templates.mcp(name, lowerName);
  }

  for (const [filename, content] of Object.entries(files)) {
    const filepath = join(resourcePath, filename);
    if (existsSync(filepath)) {
      console.warn(`  ! Skipped: ${filename} (already exists)`);
    } else {
      writeFileSync(filepath, content);
      console.log(`  + Created: ${filename}`);
    }
  }

  // Generate test file
  const testsDir = join(process.cwd(), "tests");
  if (!existsSync(testsDir)) {
    mkdirSync(testsDir, { recursive: true });
  }
  const testPath = join(testsDir, `${lowerName}.test.${ext}`);
  if (!existsSync(testPath)) {
    writeFileSync(testPath, templates.test(name, lowerName));
    console.log(`  + Created: tests/${lowerName}.test.${ext}`);
  }

  const camel = toCamelCase(name);
  const isMultiTenant = readProjectConfig().tenant === "multi";

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                    Resource Generated                         ║
╚═══════════════════════════════════════════════════════════════╝

Next steps:

1. Register in src/resources/index.${ext}:
   import ${camel}Resource from './${lowerName}/${lowerName}.resource.js';

   export const resources = [
     // ... existing resources
     ${camel}Resource,
   ];

2. Customize the model schema in:
   src/resources/${lowerName}/${lowerName}.model.${ext}

3. Adjust permissions in ${lowerName}.resource.${ext}:
${
  isMultiTenant
    ? `   - requireAuth()          → any authenticated user
   - requireRoles(['admin']) → specific platform roles`
    : `   - requireAuth()          → any authenticated user
   - requireRoles(['admin']) → specific platform roles`
}

4. Run tests:
   npm test
${
  includeMcp
    ? `
5. MCP tools file created: ${lowerName}.mcp.${ext}
   Uncomment and customize the example tools.
   Import and add to extraTools in your mcpPlugin config.
`
    : ""
}`);
}

/**
 * Generate a single file
 */
async function generateFile(
  name: string,
  lowerName: string,
  resourcePath: string,
  fileType: string,
  template: (name: string, fileName: string) => string,
  ext: string,
): Promise<void> {
  console.log(`\nGenerating ${fileType}: ${name}...\n`);

  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  + Created: src/resources/${lowerName}/`);
  }

  const filename = `${lowerName}.${fileType}.${ext}`;
  const filepath = join(resourcePath, filename);

  if (existsSync(filepath)) {
    throw new Error(`${filename} already exists. Remove it first or use a different name.`);
  }

  writeFileSync(filepath, template(name, lowerName));
  console.log(`  + Created: ${filename}`);
}
