/**
 * Arc CLI - Generate Command
 *
 * Scaffolds resources with consistent naming:
 * - src/resources/product/product.model.ts
 * - src/resources/product/product.repository.ts
 * - src/resources/product/product.resource.ts
 * - src/resources/product/product.controller.ts
 * - src/resources/product/product.schemas.ts
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { pluralize } from "../utils/pluralize.js";

interface ArcProjectConfig {
  adapter?: "mongokit" | "custom";
  auth?: "jwt" | "better-auth";
  tenant?: "multi" | "single";
  typescript?: boolean;
}

// Read .arcrc project config (written by `arc init`)
function readProjectConfig(): ArcProjectConfig {
  try {
    const rcPath = join(process.cwd(), ".arcrc");
    return JSON.parse(readFileSync(rcPath, "utf-8"));
  } catch {
    return {};
  }
}

// Check if TypeScript project
function isTypeScriptProject(): boolean {
  return existsSync(join(process.cwd(), "tsconfig.json"));
}

// Templates
function getTemplates(ts: boolean, config: ArcProjectConfig = {}) {
  const isMultiTenant = config.tenant === "multi";

  return {
    model: (name: string) => `/**
 * ${name} Model
 * Generated by Arc CLI
 */

import mongoose${ts ? ", { type HydratedDocument }" : ""} from 'mongoose';

const { Schema } = mongoose;
${
  ts
    ? `
export interface I${name} {
  name: string;
  description?: string;
  isActive: boolean;
}

export type ${name}Document = HydratedDocument<I${name}>;
`
    : ""
}
const ${name.toLowerCase()}Schema = new Schema${ts ? `<I${name}>` : ""}(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

// Indexes
${name.toLowerCase()}Schema.index({ name: 1 });
${name.toLowerCase()}Schema.index({ isActive: 1 });

const ${name} = mongoose.models.${name} || mongoose.model('${name}', ${name.toLowerCase()}Schema);
export default ${name};
`,

    repository: (name: string) => `/**
 * ${name} Repository
 * Generated by Arc CLI
 */

import {
  Repository,
  methodRegistryPlugin,
  softDeletePlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
import ${name} from './${name.toLowerCase()}.model.js';

class ${name}Repository extends Repository {
  constructor() {
    super(${name}, [
      methodRegistryPlugin(),
      softDeletePlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find all active records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }
}

const ${name.toLowerCase()}Repository = new ${name}Repository();
export default ${name.toLowerCase()}Repository;
export { ${name}Repository };
`,

    controller: (name: string) => `/**
 * ${name} Controller
 * Generated by Arc CLI
 *
 * Note: defineResource() auto-creates a controller from the adapter.
 * Only create a custom controller when you need custom methods.
 */

import { BaseController } from '@classytic/arc';
import ${name.toLowerCase()}Repository from './${name.toLowerCase()}.repository.js';

class ${name}Controller extends BaseController {
  constructor() {
    super(${name.toLowerCase()}Repository, {
      resourceName: '${name.toLowerCase()}',
    });
  }

  // Add custom controller methods here
}

const ${name.toLowerCase()}Controller = new ${name}Controller();
export default ${name.toLowerCase()}Controller;
`,

    schemas: (name: string) => `/**
 * ${name} Schemas
 * Generated by Arc CLI
 */

import ${name} from './${name.toLowerCase()}.model.js';
import { buildCrudSchemasFromModel } from '@classytic/mongokit/utils';

/**
 * CRUD Schemas with Field Rules
 */
const crudSchemas = buildCrudSchemasFromModel(${name}, {
  strictAdditionalProperties: true,
  fieldRules: {
    // Mark fields as system-managed (excluded from create/update)
    // deletedAt: { systemManaged: true },
  },
  query: {
    filterableFields: {
      isActive: 'boolean',
      createdAt: 'date',
    },
  },
});

export default crudSchemas;
`,

    resource: (name: string) => {
      const useMongoKit = config.adapter === "mongokit" || !config.adapter;
      const queryParserImport = useMongoKit
        ? `\nimport { QueryParser } from '@classytic/mongokit';\n\nconst queryParser = new QueryParser();\n`
        : "";
      const queryParserConfig = useMongoKit ? `\n  queryParser,` : "";

      return isMultiTenant
        ? `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource, createMongooseAdapter } from '@classytic/arc';
import { requireOrgMembership, requireOrgRole } from '@classytic/arc/permissions';
import ${name}${ts ? `, { type I${name} }` : ""} from './${name.toLowerCase()}.model.js';
import ${name.toLowerCase()}Repository from './${name.toLowerCase()}.repository.js';${queryParserImport}

const ${name.toLowerCase()}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${name.toLowerCase()}',
  adapter: createMongooseAdapter(${name}, ${name.toLowerCase()}Repository),${queryParserConfig}
  presets: ['softDelete'],
  permissions: {
    list: requireOrgMembership(),
    get: requireOrgMembership(),
    create: requireOrgRole('admin'),
    update: requireOrgRole('admin'),
    delete: requireOrgRole('admin'),
  },
});

export default ${name.toLowerCase()}Resource;
`
        : `/**
 * ${name} Resource
 * Generated by Arc CLI
 */

import { defineResource, createMongooseAdapter } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import ${name}${ts ? `, { type I${name} }` : ""} from './${name.toLowerCase()}.model.js';
import ${name.toLowerCase()}Repository from './${name.toLowerCase()}.repository.js';${queryParserImport}

const ${name.toLowerCase()}Resource = defineResource${ts ? `<I${name}>` : ""}({
  name: '${name.toLowerCase()}',
  adapter: createMongooseAdapter(${name}, ${name.toLowerCase()}Repository),${queryParserConfig}
  presets: ['softDelete'],
  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireRoles(['admin']),
    update: requireRoles(['admin']),
    delete: requireRoles(['admin']),
  },
});

export default ${name.toLowerCase()}Resource;
`;
    },

    test: (name: string) => `/**
 * ${name} Tests
 * Generated by Arc CLI
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createMinimalTestApp } from '@classytic/arc/testing';
${ts ? "import type { FastifyInstance } from 'fastify';\n" : ""}import ${name.toLowerCase()}Resource from '../src/resources/${name.toLowerCase()}/${name.toLowerCase()}.resource.js';

describe('${name} Resource', () => {
  let app${ts ? ": FastifyInstance" : ""};

  beforeAll(async () => {
    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/arc-app-test';
    await mongoose.connect(testDbUri);

    app = createMinimalTestApp();
    await app.register(${name.toLowerCase()}Resource.toPlugin());
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await mongoose.connection.close();
  });

  describe('GET /${pluralize(name.toLowerCase())}', () => {
    it('should return a list', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/${pluralize(name.toLowerCase())}',
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('docs');
    });
  });
});
`,
  };
}

/**
 * Generate command handler
 */
export async function generate(
  type: string | undefined,
  args: string[],
): Promise<void> {
  if (!type) {
    throw new Error(
      "Missing type argument\nUsage: arc generate <resource|controller|model|repository|schemas> <name>",
    );
  }

  const [name] = args;
  if (!name) {
    throw new Error(
      "Missing name argument\nUsage: arc generate <type> <name>\nExample: arc generate resource product",
    );
  }

  // Capitalize first letter
  const capitalizedName = name.charAt(0).toUpperCase() + name.slice(1);
  const lowerName = name.toLowerCase();

  // Detect project config
  const projectConfig = readProjectConfig();
  const ts = projectConfig.typescript ?? isTypeScriptProject();
  const ext = ts ? "ts" : "js";
  const templates = getTemplates(ts, projectConfig);

  // Resource path: src/resources/<name>/
  const resourcePath = join(process.cwd(), "src", "resources", lowerName);

  switch (type) {
    case "resource":
    case "r":
      await generateResource(
        capitalizedName,
        lowerName,
        resourcePath,
        templates,
        ext,
      );
      break;

    case "controller":
    case "c":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "controller",
        templates.controller,
        ext,
      );
      break;

    case "model":
    case "m":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "model",
        templates.model,
        ext,
      );
      break;

    case "repository":
    case "repo":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "repository",
        templates.repository,
        ext,
      );
      break;

    case "schemas":
    case "s":
      await generateFile(
        capitalizedName,
        lowerName,
        resourcePath,
        "schemas",
        templates.schemas,
        ext,
      );
      break;

    default:
      throw new Error(
        `Unknown type: ${type}\nAvailable types: resource, controller, model, repository, schemas`,
      );
  }
}

/**
 * Generate a full resource
 */
async function generateResource(
  name: string,
  lowerName: string,
  resourcePath: string,
  templates: ReturnType<typeof getTemplates>,
  ext: string,
): Promise<void> {
  console.log(`\nGenerating resource: ${name}...\n`);

  // Create directory
  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  + Created: src/resources/${lowerName}/`);
  }

  // Generate files (defineResource() auto-creates controller, no schemas needed)
  const files: Record<string, string> = {
    [`${lowerName}.model.${ext}`]: templates.model(name),
    [`${lowerName}.repository.${ext}`]: templates.repository(name),
    [`${lowerName}.resource.${ext}`]: templates.resource(name),
  };

  for (const [filename, content] of Object.entries(files)) {
    const filepath = join(resourcePath, filename);
    if (existsSync(filepath)) {
      console.warn(`  ! Skipped: ${filename} (already exists)`);
    } else {
      writeFileSync(filepath, content);
      console.log(`  + Created: ${filename}`);
    }
  }

  // Generate test file
  const testsDir = join(process.cwd(), "tests");
  if (!existsSync(testsDir)) {
    mkdirSync(testsDir, { recursive: true });
  }
  const testPath = join(testsDir, `${lowerName}.test.${ext}`);
  if (!existsSync(testPath)) {
    writeFileSync(testPath, templates.test(name));
    console.log(`  + Created: tests/${lowerName}.test.${ext}`);
  }

  const isMultiTenant = readProjectConfig().tenant === "multi";

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                    Resource Generated                         ║
╚═══════════════════════════════════════════════════════════════╝

Next steps:

1. Register in src/resources/index.${ext}:
   import ${lowerName}Resource from './${lowerName}/${lowerName}.resource.js';

   export const resources = [
     // ... existing resources
     ${lowerName}Resource,
   ];

2. Customize the model schema in:
   src/resources/${lowerName}/${lowerName}.model.${ext}

3. Adjust permissions in ${lowerName}.resource.${ext}:
${
  isMultiTenant
    ? `   - requireOrgMembership()  → any org member
   - requireOrgRole('admin') → specific org roles`
    : `   - requireAuth()          → any authenticated user
   - requireRoles(['admin']) → specific platform roles`
}

4. Run tests:
   npm test
`);
}

/**
 * Generate a single file
 */
async function generateFile(
  name: string,
  lowerName: string,
  resourcePath: string,
  fileType: string,
  template: (name: string) => string,
  ext: string,
): Promise<void> {
  console.log(`\nGenerating ${fileType}: ${name}...\n`);

  if (!existsSync(resourcePath)) {
    mkdirSync(resourcePath, { recursive: true });
    console.log(`  + Created: src/resources/${lowerName}/`);
  }

  const filename = `${lowerName}.${fileType}.${ext}`;
  const filepath = join(resourcePath, filename);

  if (existsSync(filepath)) {
    throw new Error(
      `${filename} already exists. Remove it first or use a different name.`,
    );
  }

  writeFileSync(filepath, template(name));
  console.log(`  + Created: ${filename}`);
}

export default generate;
